#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_RetourGrUnDe
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3 - Mehrlieferung mit Berechnung", 0)]
		_3MehrlieferungMitBerechnung = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("4 - Nicht bestellter Artikel", 1)]
		_4NichtBestellterArtikel = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("50 - Kulanz", 5)]
		_50Kulanz = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("5 - Doppelt geliefert", 2)]
		_5DoppeltGeliefert = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("6 - Zu spät geliefert", 3)]
		_6ZuSpTGeliefert = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("9 - Lieferung ohne Berechnung", 4)]
		_9LieferungOhneBerechnung = 100000004,
	}
}
#pragma warning restore CS1591
