#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_Comp_ABonneMent_C
	{
		
		/// <summary>
		/// baurechtsreport
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Baurechts-Report", 1, "#0000ff", "baurechtsreport", "baurechtsreport")]
		BaurechtsReport = 100000000,
		
		/// <summary>
		/// branchenreport
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Branchen-Report", 0, "#0000ff", "branchenreport", "branchenreport")]
		BranchenReport = 100000001,
		
		/// <summary>
		/// branchenreportprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Branchenreport PRINT DE", 2, "#0000ff", "branchenreportprintde", "branchenreportprintde")]
		BranchenreportPrintDe = 100000002,
		
		/// <summary>
		/// businessnetzwerknewsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Newsletter", 3, "#0000ff", "businessnetzwerknewsletter", "businessnetzwerknewsletter")]
		BusinessNetzwerkNewsletter = 100000003,
		
		/// <summary>
		/// DerHandel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Der Handel", 4, "#0000ff", "DerHandel", "DerHandel")]
		DerHandel = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI-Geschäftsbrief", 40)]
		EdiGeschFtsbrief = 100000040,
		
		/// <summary>
		/// ESHHalbjahresergebnisse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Halbjahresergebnisse", 5, "#0000ff", "ESHHalbjahresergebnisse", "ESHHalbjahresergebnisse")]
		EshHalbjahresergebnisse = 100000005,
		
		/// <summary>
		/// eurodiynewsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Newsletter", 6, "#0000ff", "eurodiynewsletter", "eurodiynewsletter")]
		EuroDiyNewsletter = 100000006,
		
		/// <summary>
		/// geburtstagskarte
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geburtstagskarte", 7, "#0000ff", "geburtstagskarte", "geburtstagskarte")]
		Geburtstagskarte = 100000007,
		
		/// <summary>
		/// GeschaeftsberichtPDFEN
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geschäftsbericht PDF EN", 8, "#0000ff", "GeschaeftsberichtPDFEN", "GeschaeftsberichtPDFEN")]
		GeschFtsberichtPdfEn = 100000008,
		
		/// <summary>
		/// geschaeftsberichtprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geschäftsbericht PRINT DE", 9, "#0000ff", "geschaeftsberichtprintde", "geschaeftsberichtprintde")]
		GeschFtsberichtPrintDe = 100000009,
		
		/// <summary>
		/// geschaeftsberichtprinten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geschäftsbericht PRINT EN", 10, "#0000ff", "geschaeftsberichtprinten", "geschaeftsberichtprinten")]
		GeschFtsberichtPrintEn = 100000010,
		
		/// <summary>
		/// greenmotonewsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GreenMoto Newsletter", 11, "#0000ff", "greenmotonewsletter", "greenmotonewsletter")]
		GreenmotoNewsletter = 100000011,
		
		/// <summary>
		/// HWSNewsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWS Newsletter", 12, "#0000ff", "HWSNewsletter", "HWSNewsletter")]
		HwsNewsletter = 100000012,
		
		/// <summary>
		/// ISOZertifizierung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ISO Zertifizierung", 13, "#0000ff", "ISOZertifizierung", "ISOZertifizierung")]
		IsoZertifizierung = 100000013,
		
		/// <summary>
		/// konjunkturbarometerprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Konjunkturbarometer PRINT DE", 15, "#0000ff", "konjunkturbarometerprintde", "konjunkturbarometerprintde")]
		KonjunkturbarometerPrintDe = 100000015,
		
		/// <summary>
		/// konjunkturreportprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Konjunktur-Report PRINT DE", 14, "#0000ff", "konjunkturreportprintde", "konjunkturreportprintde")]
		KonjunkturReportPrintDe = 100000014,
		
		/// <summary>
		/// Lagerlisten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lagerlisten", 16, "#0000ff", "Lagerlisten", "Lagerlisten")]
		Lagerlisten = 100000016,
		
		/// <summary>
		/// mediadatenprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mediadaten PRINT DE", 17, "#0000ff", "mediadatenprintde", "mediadatenprintde")]
		MediadatenPrintDe = 100000017,
		
		/// <summary>
		/// nachhaltigkeitsberichtprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nachhaltigkeitsbericht PRINT DE", 18, "#0000ff", "nachhaltigkeitsberichtprintde", "nachhaltigkeitsberichtprintde")]
		NachhaltigkeitsberichtPrintDe = 100000018,
		
		/// <summary>
		/// Pressegespraech
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pressegespräch", 19, "#0000ff", "Pressegespraech", "Pressegespraech")]
		PressegesprCh = 100000019,
		
		/// <summary>
		/// presseinformation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Presseinformation", 20, "#0000ff", "presseinformation", "presseinformation")]
		Presseinformation = 100000020,
		
		/// <summary>
		/// pvhmagpdfen
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH Mag. PDF EN", 21, "#0000ff", "pvhmagpdfen", "pvhmagpdfen")]
		PvhMagPdfEn = 100000021,
		
		/// <summary>
		/// pvhmagprintde
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH Mag. PRINT DE", 22, "#0000ff", "pvhmagprintde", "pvhmagprintde")]
		PvhMagPrintDe = 100000022,
		
		/// <summary>
		/// SPARPLATZRahmenabkommen
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SPARPLATZ/Rahmenabkommen", 23, "#0000ff", "SPARPLATZRahmenabkommen", "SPARPLATZRahmenabkommen")]
		SparplatzRahmenabkommen = 100000023,
		
		/// <summary>
		/// TechnischerHandelFKAktionen
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel FK Aktionen", 24, "#0000ff", "TechnischerHandelFKAktionen", "TechnischerHandelFKAktionen")]
		TechnischerHandelFkAktionen = 100000024,
		
		/// <summary>
		/// TechnischerHandelFKNewsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel FK Newsletter", 25, "#0000ff", "TechnischerHandelFKNewsletter", "TechnischerHandelFKNewsletter")]
		TechnischerHandelFkNewsletter = 100000025,
		
		/// <summary>
		/// Tourenaenderung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tourenänderung", 26, "#0000ff", "Tourenaenderung", "Tourenaenderung")]
		TourenNderung = 100000026,
		
		/// <summary>
		/// WeihnachtskarteGeschenk
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/Geschenk", 27, "#0000ff", "WeihnachtskarteGeschenk", "WeihnachtskarteGeschenk")]
		WeihnachtskarteGeschenk = 100000027,
		
		/// <summary>
		/// weihnachtskarten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarten", 37, "#0000ff", "weihnachtskarten", "weihnachtskarten")]
		Weihnachtskarten = 100000036,
		
		/// <summary>
		/// WeihnachtskarteNiederlassungrs
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/Niederlassung r.s.", 28, "#0000ff", "WeihnachtskarteNiederlassungrs", "WeihnachtskarteNiederlassungrs")]
		WeihnachtskarteNiederlassungRS = 100000028,
		
		/// <summary>
		/// Weihnachtskartepersoenlich
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich", 29, "#0000ff", "Weihnachtskartepersoenlich", "Weihnachtskartepersoenlich")]
		WeihnachtskartePersNlich = 100000029,
		
		/// <summary>
		/// Weihnachtskarte/persönlich/digital
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich/digital", 30, "#0000ff", "Weihnachtskarte/persönlich/digital")]
		WeihnachtskartePersNlichDigital = 100000039,
		
		/// <summary>
		/// WeihnachtskartepersoenlichEDEInternational
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich EDE International", 31, "#0000ff", "WeihnachtskartepersoenlichEDEInternational", "WeihnachtskartepersoenlichEDEInternational")]
		WeihnachtskartePersNlichEdeInternational = 100000030,
		
		/// <summary>
		/// WeihnachtskartepersoenlichGBME
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich GBME", 32, "#0000ff", "WeihnachtskartepersoenlichGBME", "WeihnachtskartepersoenlichGBME")]
		WeihnachtskartePersNlichGbme = 100000031,
		
		/// <summary>
		/// WeihnachtskartepersoenlichGF1
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich GF 1", 33, "#0000ff", "WeihnachtskartepersoenlichGF1", "WeihnachtskartepersoenlichGF1")]
		WeihnachtskartePersNlichGf1 = 100000032,
		
		/// <summary>
		/// WeihnachtskartepersoenlichGF2
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich GF 2", 34, "#0000ff", "WeihnachtskartepersoenlichGF2", "WeihnachtskartepersoenlichGF2")]
		WeihnachtskartePersNlichGf2 = 100000033,
		
		/// <summary>
		/// WeihnachtskartepersoenlichGF3
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich GF 3", 35, "#0000ff", "WeihnachtskartepersoenlichGF3", "WeihnachtskartepersoenlichGF3")]
		WeihnachtskartePersNlichGf3 = 100000034,
		
		/// <summary>
		/// WeihnachtskartepersoenlichGF4
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weihnachtskarte/persönlich GF 4", 36, "#0000ff", "WeihnachtskartepersoenlichGF4", "WeihnachtskartepersoenlichGF4")]
		WeihnachtskartePersNlichGf4 = 100000035,
		
		/// <summary>
		/// Werbungunerwuenscht
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Werbung unerwünscht", 38, "#0000ff", "Werbungunerwuenscht", "Werbungunerwuenscht")]
		WerbungUnerwNscht = 100000037,
		
		/// <summary>
		/// ZDFFlyer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ZDF-Flyer", 39, "#0000ff", "ZDFFlyer", "ZDFFlyer")]
		ZdfFlyer = 100000038,
	}
}
#pragma warning restore CS1591
