#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_AnFrAGenKLaSsIfIZIeRunG
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Allg. Information EDE Intern", 1)]
		AllgInformationEdeIntern = 100001004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Anfragen", 2, "#ffffff")]
		Anfragen = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Angebot", 3, "#ffffff")]
		Angebot = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Artikel defekt", 4, "#ffffff")]
		ArtikelDefekt = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auftrag absagen / ändern lt. FB", 5, "#ffffff")]
		AuftragAbsagenNdernLtFb = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auftragseingang", 6, "#ffffff")]
		Auftragseingang = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auftragsänderung vom MG", 7)]
		AuftragsNderungVomMg = 100001011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Avis", 8, "#ffffff")]
		Avis = 100001001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Beleg angefordert", 9, "#ffffff")]
		BelegAngefordert = 100000014,
		
		/// <summary>
		/// Fachbereichsstatus
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bestellung / Lagerbesorgung ", 39, "#e0e9ff", "Fachbereichsstatus")]
		BestellungLagerbesorgung = 100001012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Buchungsanzeige", 11, "#ffffff")]
		Buchungsanzeige = 100000018,
		
		/// <summary>
		/// Fachbereichsstatus
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dokument", 40, "#e0e9ff", "Fachbereichsstatus")]
		Dokument = 100001013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Doppelte Aufträge", 10)]
		DoppelteAuftrGe = 100001010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI Fehlermeldung", 12)]
		EdiFehlermeldung = 100001007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falschbestellung durch Mitglied", 13)]
		FalschbestellungDurchMitglied = 100000104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falschlieferung", 14, "#ffffff")]
		Falschlieferung = 100000105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fehlmenge", 15)]
		Fehlmenge = 100000101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fracht Versandkosten", 17, "#ffffff")]
		FrachtVersandkosten = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intern", 16, "#ffffff")]
		Intern = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kontaktdaten Endkunde", 18, "#ffffff")]
		KontaktdatenEndkunde = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kosten für 2. Zustellung", 19, "#ffffff")]
		KostenFR2Zustellung = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kosten für Umverfügung", 20, "#ffffff")]
		KostenFRUmverfGung = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kulanz", 21, "#ffffff")]
		Kulanz = 100000007,
		
		/// <summary>
		/// Fachbereichsstatus
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lager", 41, "#e0e9ff", "Fachbereichsstatus")]
		Lager = 100001014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lagergeld", 22, "#ffffff")]
		Lagergeld = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Liefertermin", 23, "#ffffff")]
		Liefertermin = 100000003,
		
		/// <summary>
		/// Fachbereichsstatus
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Muster", 42, "#e0e9ff", "Fachbereichsstatus")]
		Muster = 100001015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Änderung / Umbuchung Rechnung", 0)]
		NderungUmbuchungRechnung = 100001003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nicht SC weitergeleitet", 24)]
		NichtScWeitergeleitet = 100001006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preisreklamation", 25, "#ffffff")]
		Preisreklamation = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Retoure", 26, "#ffffff")]
		Retoure = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Schlechte Verpackung", 27, "#ffffff")]
		SchlechteVerpackung = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sendungsverfolgung Verlust einer Lieferung", 28, "#ffffff")]
		SendungsverfolgungVerlustEinerLieferung = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sicherheitsdatenblatt", 29, "#ffffff")]
		Sicherheitsdatenblatt = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sonstiges / Allgemein", 30)]
		SonstigesAllgemein = 100001000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Storno der Bestellung", 31, "#ffffff")]
		StornoDerBestellung = 100000999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportschaden", 32, "#ffffff")]
		Transportschaden = 100000109,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unzustellbare E-Mail / Abwesenheitsnachricht", 34)]
		UnzustellbareEMailAbwesenheitsnachricht = 100001008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UPS Rückmeldung", 33)]
		UpsRCkmeldung = 100001005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Verspätete Zustellung", 35, "#ffffff")]
		VerspTeteZustellung = 100001009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Werksfehler HT", 36, "#ffffff")]
		WerksfehlerHt = 100000703,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zertifikatsanfrage", 37, "#ffffff")]
		Zertifikatsanfrage = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zustellung nicht möglich", 38)]
		ZustellungNichtMGlich = 100001002,
	}
}
#pragma warning restore CS1591
