#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_FuNc_Company_Norm_C
	{
		
		/// <summary>
		/// Assistenz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assistenz", 0, "", "Assistenz", "Assistenz")]
		Assistenz = 100000001,
		
		/// <summary>
		/// Aussendienstmitarbeiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Außendienstmitarbeiter", 1, "", "Aussendienstmitarbeiter", "Aussendienstmitarbeiter")]
		AuEndienstmitarbeiter = 100000002,
		
		/// <summary>
		/// Betriebsleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Betriebsleiter", 2, "", "Betriebsleiter", "Betriebsleiter")]
		Betriebsleiter = 100000003,
		
		/// <summary>
		/// Buchhalter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Buchhalter", 3, "", "Buchhalter", "Buchhalter")]
		Buchhalter = 100000004,
		
		/// <summary>
		/// eBusinessManager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eBusinessManager", 4, "", "eBusinessManager", "eBusinessManager")]
		Ebusinessmanager = 100000005,
		
		/// <summary>
		/// Einkaufsleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Einkaufsleiter", 5, "", "Einkaufsleiter", "Einkaufsleiter")]
		Einkaufsleiter = 100000006,
		
		/// <summary>
		/// Einkaeufer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Einkäufer", 6, "", "Einkaeufer", "Einkaeufer")]
		EinkUfer = 100000007,
		
		/// <summary>
		/// ExternerBerater
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ExternerBerater", 7, "", "ExternerBerater", "ExternerBerater")]
		Externerberater = 100000008,
		
		/// <summary>
		/// Fachberater
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fachberater", 10, "", "Fachberater", "Fachberater")]
		Fachberater = 100000009,
		
		/// <summary>
		/// Fachbereichsleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fachbereichsleiter", 11, "", "Fachbereichsleiter", "Fachbereichsleiter")]
		Fachbereichsleiter = 100000010,
		
		/// <summary>
		/// Gebietsverkaufsleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gebietsverkaufsleiter", 12, "", "Gebietsverkaufsleiter", "Gebietsverkaufsleiter")]
		Gebietsverkaufsleiter = 100000011,
		
		/// <summary>
		/// Handelsvertreter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Handelsvertreter", 13, "", "Handelsvertreter", "Handelsvertreter")]
		Handelsvertreter = 100000012,
		
		/// <summary>
		/// Journalist
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journalist", 14, "", "Journalist", "Journalist")]
		Journalist = 100000013,
		
		/// <summary>
		/// KaufmaennischerLeiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KaufmaennischerLeiter", 8, "", "KaufmaennischerLeiter", "KaufmaennischerLeiter")]
		Kaufmaennischerleiter = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 26)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// KeyAccountManager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KeyAccountManager", 15, "", "KeyAccountManager", "KeyAccountManager")]
		Keyaccountmanager = 100000014,
		
		/// <summary>
		/// Logistikleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Logistikleiter", 16, "", "Logistikleiter", "Logistikleiter")]
		Logistikleiter = 100000015,
		
		/// <summary>
		/// MarketingManager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MarketingManager", 17, "", "MarketingManager", "MarketingManager")]
		Marketingmanager = 100000016,
		
		/// <summary>
		/// NiederlassungsMarktleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Niederlassungs-/Marktleiter", 18, "", "NiederlassungsMarktleiter", "NiederlassungsMarktleiter")]
		NiederlassungsMarktleiter = 100000017,
		
		/// <summary>
		/// Personalentwickler
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Personalentwickler", 20, "", "Personalentwickler", "Personalentwickler")]
		Personalentwickler = 100000019,
		
		/// <summary>
		/// PersonohneFirma
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PersonohneFirma", 19, "", "PersonohneFirma", "PersonohneFirma")]
		Personohnefirma = 100000018,
		
		/// <summary>
		/// Produktmanager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Produktmanager", 21, "", "Produktmanager", "Produktmanager")]
		Produktmanager = 100000020,
		
		/// <summary>
		/// Projektleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Projektleiter", 22, "", "Projektleiter", "Projektleiter")]
		Projektleiter = 100000021,
		
		/// <summary>
		/// Vertriebsinnendienst
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertriebsinnendienst", 24, "", "Vertriebsinnendienst", "Vertriebsinnendienst")]
		Vertriebsinnendienst = 100000023,
		
		/// <summary>
		/// Vertriebsinnendienstleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertriebsinnendienstleiter", 9, "", "Vertriebsinnendienstleiter", "Vertriebsinnendienstleiter")]
		Vertriebsinnendienstleiter = 100000026,
		
		/// <summary>
		/// Vertriebsleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertriebsleiter", 25, "", "Vertriebsleiter", "Vertriebsleiter")]
		Vertriebsleiter = 100000024,
		
		/// <summary>
		/// VertriebsMarketingleiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertriebs-/Marketingleiter", 23, "", "VertriebsMarketingleiter", "VertriebsMarketingleiter")]
		VertriebsMarketingleiter = 100000022,
	}
}
#pragma warning restore CS1591
