#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_ContactSrc_C
	{
		
		/// <summary>
		/// EtrisBank
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Anfrage Belegkanal", 0, "#0000ff", "EtrisBank")]
		AnfrageBelegkanal = 100000048,
		
		/// <summary>
		/// BT2016Personendaten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BT 2016 Personendaten", 12, "", "BT2016Personendaten", "BT2016Personendaten")]
		Bt2016Personendaten = 100000001,
		
		/// <summary>
		/// Digitale Services Import
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Digitale Services Import", 11, "#0000ff", "Digitale Services Import", "Digitale Services Import")]
		DigitaleServicesImport = 100000037,
		
		/// <summary>
		/// ECRM
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("E-Business CRM", 13, "", "ECRM", "ECRM")]
		EBusinessCrm = 100000002,
		
		/// <summary>
		/// EDEInternationalBranchentreff2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDE International Branchentreff 2016", 14, "", "EDEInternationalBranchentreff2016", "EDEInternationalBranchentreff2016")]
		EdeInternationalBranchentreff2016 = 100000003,
		
		/// <summary>
		/// EDEInternationalISA2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDE International ISA 2016", 15, "", "EDEInternationalISA2016", "EDEInternationalISA2016")]
		EdeInternationalIsa2016 = 100000004,
		
		/// <summary>
		/// EDEInternationalLagerlistenversand2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDE International Lagerlistenversand 2016", 16, "", "EDEInternationalLagerlistenversand2016", "EDEInternationalLagerlistenversand2016")]
		EdeInternationalLagerlistenversand2016 = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI-Anbindung Nachfassaktion Lagerlieferanten  DIY RE", 2, "#0000ff")]
		EdiAnbindungNachfassaktionLagerlieferantenDiyRe = 100000046,
		
		/// <summary>
		/// EURODIYBetreuungsvertraege2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Betreuungsverträge 2016", 17, "", "EURODIYBetreuungsvertraege2016", "EURODIYBetreuungsvertraege2016")]
		EuroDiyBetreuungsvertrGe2016 = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Lagerlieferanten_Ansprechpartner_Terminsache Umsetzung EU-Verordnung 202" +
			"3_1", 1, "#0000ff")]
		EuroDiyLagerlieferantenAnsprechpartnerTerminsacheUmsetzungEuVerordnung20231 = 100000047,
		
		/// <summary>
		/// EURODIYLieferanten2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Lieferanten 2016", 18, "", "EURODIYLieferanten2016", "EURODIYLieferanten2016")]
		EuroDiyLieferanten2016 = 100000007,
		
		/// <summary>
		/// EURODIYWerkmaerkte2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Werkmärkte 2016", 19, "", "EURODIYWerkmaerkte2016", "EURODIYWerkmaerkte2016")]
		EuroDiyWerkmRkte2016 = 100000008,
		
		/// <summary>
		/// EXTRANET
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Extranet", 20, "", "EXTRANET", "EXTRANET")]
		Extranet = 100000009,
		
		/// <summary>
		/// GB1LieferantenBranchentreff2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1 Lieferanten Branchentreff 2016", 21, "", "GB1LieferantenBranchentreff2016", "GB1LieferantenBranchentreff2016")]
		Gb1LieferantenBranchentreff2016 = 100000010,
		
		/// <summary>
		/// GB1Lieferantengesamt2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1 Lieferanten gesamt 2016", 22, "", "GB1Lieferantengesamt2016", "GB1Lieferantengesamt2016")]
		Gb1LieferantenGesamt2016 = 100000011,
		
		/// <summary>
		/// GB1LieferantenISA2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1 Lieferanten ISA 2016", 23, "", "GB1LieferantenISA2016", "GB1LieferantenISA2016")]
		Gb1LieferantenIsa2016 = 100000012,
		
		/// <summary>
		/// GB1MitgliederBT2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1 Mitglieder BT 2016", 24, "", "GB1MitgliederBT2016", "GB1MitgliederBT2016")]
		Gb1MitgliederBt2016 = 100000013,
		
		/// <summary>
		/// GB1Mitgliedergesamt2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1Mitglieder gesamt 2016", 26, "", "GB1Mitgliedergesamt2016", "GB1Mitgliedergesamt2016")]
		Gb1MitgliederGesamt2016 = 100000015,
		
		/// <summary>
		/// GB1MitgliederISA2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 1 Mitglieder ISA 2016", 25, "", "GB1MitgliederISA2016", "GB1MitgliederISA2016")]
		Gb1MitgliederIsa2016 = 100000014,
		
		/// <summary>
		/// GB2LieferantenBauelemente2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB2 Lieferanten Bauelemente 2016", 37, "", "GB2LieferantenBauelemente2016", "GB2LieferantenBauelemente2016")]
		Gb2LieferantenBauelemente2016 = 100000026,
		
		/// <summary>
		/// GB2MitgliederBauelemente2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB2 Mitglieder Bauelemente 2016", 38, "", "GB2MitgliederBauelemente2016", "GB2MitgliederBauelemente2016")]
		Gb2MitgliederBauelemente2016 = 100000027,
		
		/// <summary>
		/// GB3FKMitgliederBG2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 FK Mitglieder BG 2016", 27, "", "GB3FKMitgliederBG2016", "GB3FKMitgliederBG2016")]
		Gb3FkMitgliederBg2016 = 100000016,
		
		/// <summary>
		/// GB3ISALieferantenMitgliederBE2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 ISA Lieferanten Mitglieder BE 2016", 28, "", "GB3ISALieferantenMitgliederBE2016", "GB3ISALieferantenMitgliederBE2016")]
		Gb3IsaLieferantenMitgliederBe2016 = 100000017,
		
		/// <summary>
		/// GB3ISALieferantenMitgliederBG2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 ISA Lieferanten Mitglieder BG 2016", 29, "", "GB3ISALieferantenMitgliederBG2016", "GB3ISALieferantenMitgliederBG2016")]
		Gb3IsaLieferantenMitgliederBg2016 = 100000018,
		
		/// <summary>
		/// GB3ISALieferantenMitgliederSWT2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 ISA Lieferanten Mitglieder SWT 2016", 30, "", "GB3ISALieferantenMitgliederSWT2016", "GB3ISALieferantenMitgliederSWT2016")]
		Gb3IsaLieferantenMitgliederSwt2016 = 100000019,
		
		/// <summary>
		/// GB3LieferantenBG2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 Lieferanten BG 2016", 31, "", "GB3LieferantenBG2016", "GB3LieferantenBG2016")]
		Gb3LieferantenBg2016 = 100000020,
		
		/// <summary>
		/// GB3LieferantenMasterliste2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 Lieferanten Masterliste 2016", 32, "", "GB3LieferantenMasterliste2016", "GB3LieferantenMasterliste2016")]
		Gb3LieferantenMasterliste2016 = 100000021,
		
		/// <summary>
		/// GB3MitgliederBGK2015
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 3 Mitglieder BGK 2015", 33, "", "GB3MitgliederBGK2015", "GB3MitgliederBGK2015")]
		Gb3MitgliederBgk2015 = 100000022,
		
		/// <summary>
		/// LIEFARBSCHUTZ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 4 Lieferanten ArbeitsschutDS z", 44, "", "LIEFARBSCHUTZ", "LIEFARBSCHUTZ")]
		Gb4LieferantenArbeitsschutdsZ = 100000033,
		
		/// <summary>
		/// TECHHANDFBL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 4 Technischer Handel Fachbeiratsliste Fachkreis TH", 45, "", "TECHHANDFBL", "TECHHANDFBL")]
		Gb4TechnischerHandelFachbeiratslisteFachkreisTh = 100000034,
		
		/// <summary>
		/// TECHHANDLIEFLAGER122016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 4 Technischer Handel Lieferanten Lager TH Stand 12.2016", 46, "", "TECHHANDLIEFLAGER122016", "TECHHANDLIEFLAGER122016")]
		Gb4TechnischerHandelLieferantenLagerThStand122016 = 100000035,
		
		/// <summary>
		/// TECHHANDWERKSTATTMAT012015
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB 4 Technischer Handel Lieferantenliste Werkstattmat. 01.2015", 47, "", "TECHHANDWERKSTATTMAT012015", "TECHHANDWERKSTATTMAT012015")]
		Gb4TechnischerHandelLieferantenlisteWerkstattmat012015 = 100000036,
		
		/// <summary>
		/// GBMABranchentreff2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB MA Branchentreff 2016", 34, "", "GBMABranchentreff2016", "GBMABranchentreff2016")]
		GbMaBranchentreff2016 = 100000023,
		
		/// <summary>
		/// GBMALieferantentagedCToolineo2015
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB MA Lieferantentag edC Toolineo 2015", 35, "", "GBMALieferantentagedCToolineo2015", "GBMALieferantentagedCToolineo2015")]
		GbMaLieferantentagEdcToolineo2015 = 100000024,
		
		/// <summary>
		/// GBMEJuJU2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB ME JuJU 2016", 36, "", "GBMEJuJU2016", "GBMEJuJU2016")]
		GbMeJuju2016 = 100000025,
		
		/// <summary>
		/// ISA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ISA", 39, "", "ISA", "ISA")]
		Isa = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kampagne für Präzisionswerkzeuge", 3, "#0000ff")]
		KampagneFRPrZisionswerkzeuge = 100000044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 48)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// Lagerlieferanten Massenmailing Update GF-Stammdaten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lagerlieferanten Massenmailing Update GF-Stammdaten", 8, "#0000ff", "Lagerlieferanten Massenmailing Update GF-Stammdaten", "Lagerlieferanten Massenmailing Update GF-Stammdaten")]
		LagerlieferantenMassenmailingUpdateGfStammdaten = 100000038,
		
		/// <summary>
		/// Lagerlieferanten Massenmailing Update GF-Stammdaten - korrigierte Kontakte für Zweitversand
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lagerlieferanten Massenmailing Update GF-Stammdaten - korrigierte Kontakte für Zw" +
			"eitversand", 9, "#0000ff", "Lagerlieferanten Massenmailing Update GF-Stammdaten - korrigierte Kontakte für Zw" +
			"eitversand", "korrigierte Kontakte für Zweitversand")]
		LagerlieferantenMassenmailingUpdateGfStammdatenKorrigierteKontakteFRZweitversand = 100000040,
		
		/// <summary>
		/// Lagerlieferanten Massenmailing Update GF-Stammdaten - zweite Erinnerung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lagerlieferanten Massenmailing Update GF-Stammdaten - zweite Erinnerung", 10, "#0000ff", "Lagerlieferanten Massenmailing Update GF-Stammdaten - zweite Erinnerung")]
		LagerlieferantenMassenmailingUpdateGfStammdatenZweiteErinnerung = 100000045,
		
		/// <summary>
		/// von Mehmet Özcan
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marketingliste Regionalveranstaltung LE-Shop (Mgl.-Mgt.)", 5, "#0000ff", "von Mehmet Özcan")]
		MarketinglisteRegionalveranstaltungLeShopMglMgt = 100000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Massenmailing Umfrage Optimierung des Versorgungs- und Beschaffungssortiments (au" +
			"s dem Team Handwerkzeuge)", 4, "#0000ff")]
		MassenmailingUmfrageOptimierungDesVersorgungsUndBeschaffungssortimentsAusDemTeamHandwerkzeuge = 100000043,
		
		/// <summary>
		/// PVHSystemeLieferanten2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH-Systeme Lieferanten 2016", 40, "", "PVHSystemeLieferanten2016", "PVHSystemeLieferanten2016")]
		PvhSystemeLieferanten2016 = 100000029,
		
		/// <summary>
		/// PVHSystemeMitglieder2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH-Systeme Mitglieder 2016", 41, "", "PVHSystemeMitglieder2016", "PVHSystemeMitglieder2016")]
		PvhSystemeMitglieder2016 = 100000030,
		
		/// <summary>
		/// ToolineoAnsprechpartner2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Toolineo Ansprechpartner 2016", 42, "", "ToolineoAnsprechpartner2016", "ToolineoAnsprechpartner2016")]
		ToolineoAnsprechpartner2016 = 100000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertiefungsveranstaltung: SHOPCLOUD360", 6, "#0000ff", "", "Vertiefungsveranstaltung: SHOPCLOUD360")]
		VertiefungsveranstaltungShopcloud360 = 100000041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertiefungsveranstaltung: SHOPCLOUD360 - erste Erinnerungsmail", 7, "#0000ff", "", "Vertiefungsveranstaltung: SHOPCLOUD360 - erste Erinnerungsmail")]
		VertiefungsveranstaltungShopcloud360ErsteErinnerungsmail = 100000042,
		
		/// <summary>
		/// WRMitglieder2016
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Mitglieder 2016", 43, "", "WRMitglieder2016", "WRMitglieder2016")]
		WrMitglieder2016 = 100000032,
	}
}
#pragma warning restore CS1591
