#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_KOnTAkTWUnScH_C
	{
		
		/// <summary>
		/// brief
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Brief", 1, "", "brief", "brief")]
		Brief = 100000002,
		
		/// <summary>
		/// email
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("E-Mail", 0, "", "email", "email")]
		EMail = 100000001,
		
		/// <summary>
		/// fax
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FAX", 2, "", "fax", "fax")]
		Fax = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 4)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// telefon
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telefon", 3, "", "telefon", "telefon")]
		Telefon = 100000004,
	}
}
#pragma warning restore CS1591
