#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_Role_C
	{
		
		/// <summary>
		/// allgBEKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("allg. BE Konzeptbeauftragter", 0, "", "allgBEKonzeptbeauftragter", "allgBEKonzeptbeauftragter")]
		AllgBeKonzeptbeauftragter = 100000001,
		
		/// <summary>
		/// Ansprechpartner/in für den Rechnungsversand (EDI-Services) EDI-Ansprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ansprechpartner/in für den Rechnungsversand (EDI-Services)", 1, "#0000ff", "Ansprechpartner/in für den Rechnungsversand (EDI-Services) EDI-Ansprechpartner")]
		AnsprechpartnerInFRDenRechnungsversandEdiServices = 100000148,
		
		/// <summary>
		/// ATEWZKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AT EWZ Konzeptbeauftragter", 2, "", "ATEWZKonzeptbeauftragter", "ATEWZKonzeptbeauftragter")]
		AtEwzKonzeptbeauftragter = 100000002,
		
		/// <summary>
		/// Ausbildungsverantwortlicher
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ausbildungsverantwortlicher", 3, "", "Ausbildungsverantwortlicher", "Ausbildungsverantwortlicher")]
		Ausbildungsverantwortlicher = 100000003,
		
		/// <summary>
		/// AVATECHWerbebeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AVATECH Werbebeirat", 4, "", "AVATECHWerbebeirat", "AVATECHWerbebeirat")]
		AvatechWerbebeirat = 100000004,
		
		/// <summary>
		/// BadezeitTeilnehmerZeitungsbeileger
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Badezeit Teilnehmer (Zeitungsbeileger)", 6, "", "BadezeitTeilnehmerZeitungsbeileger", "BadezeitTeilnehmerZeitungsbeileger")]
		BadezeitTeilnehmerZeitungsbeileger = 100000005,
		
		/// <summary>
		/// BauelementeAnsprechpartnerLIEF
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bauelemente Ansprechpartner LIEF", 7, "", "BauelementeAnsprechpartnerLIEF", "BauelementeAnsprechpartnerLIEF")]
		BauelementeAnsprechpartnerLief = 100000006,
		
		/// <summary>
		/// BaedersehenplanenkaufenTeilnehmer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bäder.sehen.planen.kaufen Teilnehmer", 5, "", "BaedersehenplanenkaufenTeilnehmer", "BaedersehenplanenkaufenTeilnehmer")]
		BDerSehenPlanenKaufenTeilnehmer = 100000026,
		
		/// <summary>
		/// BefestigungstechnikBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Befestigungstechnik Beirat", 8, "", "BefestigungstechnikBeirat", "BefestigungstechnikBeirat")]
		BefestigungstechnikBeirat = 100000007,
		
		/// <summary>
		/// BGKGruppeBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BGK-Gruppe Beauftragter", 9, "", "BGKGruppeBeauftragter", "BGKGruppeBeauftragter")]
		BgkGruppeBeauftragter = 100000008,
		
		/// <summary>
		/// BonusabrechnungAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bonusabrechnung Ansprechpartner", 10, "", "BonusabrechnungAnsprechpartner", "BonusabrechnungAnsprechpartner")]
		BonusabrechnungAnsprechpartner = 100000009,
		
		/// <summary>
		/// BUAufsichtsrat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BU Aufsichtsrat", 11, "", "BUAufsichtsrat", "BUAufsichtsrat")]
		BuAufsichtsrat = 100000010,
		
		/// <summary>
		/// BusinessNETZWERK1
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 1", 12, "", "BusinessNETZWERK1", "BusinessNETZWERK1")]
		BusinessNetzwerk1 = 100000011,
		
		/// <summary>
		/// BusinessNETZWERK10
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 10", 13, "", "BusinessNETZWERK10", "BusinessNETZWERK10")]
		BusinessNetzwerk10 = 100000012,
		
		/// <summary>
		/// BusinessNETZWERK11
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 11", 14, "", "BusinessNETZWERK11", "BusinessNETZWERK11")]
		BusinessNetzwerk11 = 100000013,
		
		/// <summary>
		/// BusinessNETZWERK12
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 12", 15, "", "BusinessNETZWERK12", "BusinessNETZWERK12")]
		BusinessNetzwerk12 = 100000014,
		
		/// <summary>
		/// BusinessNETZWERK2
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 2", 16, "", "BusinessNETZWERK2", "BusinessNETZWERK2")]
		BusinessNetzwerk2 = 100000015,
		
		/// <summary>
		/// BusinessNETZWERK3
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 3", 17, "", "BusinessNETZWERK3", "BusinessNETZWERK3")]
		BusinessNetzwerk3 = 100000016,
		
		/// <summary>
		/// BusinessNETZWERK4
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 4", 18, "", "BusinessNETZWERK4", "BusinessNETZWERK4")]
		BusinessNetzwerk4 = 100000017,
		
		/// <summary>
		/// BusinessNETZWERK5
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 5", 19, "", "BusinessNETZWERK5", "BusinessNETZWERK5")]
		BusinessNetzwerk5 = 100000018,
		
		/// <summary>
		/// BusinessNETZWERK6
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 6", 20, "", "BusinessNETZWERK6", "BusinessNETZWERK6")]
		BusinessNetzwerk6 = 100000019,
		
		/// <summary>
		/// BusinessNETZWERK7
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 7", 21, "", "BusinessNETZWERK7", "BusinessNETZWERK7")]
		BusinessNetzwerk7 = 100000020,
		
		/// <summary>
		/// BusinessNETZWERK8
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 8", 22, "", "BusinessNETZWERK8", "BusinessNETZWERK8")]
		BusinessNetzwerk8 = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Baubeschlag", 23, "#0000ff")]
		BusinessNetzwerkBaubeschlag = 100000147,
		
		/// <summary>
		/// BusinessNETZWERKGast
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Gast", 24, "", "BusinessNETZWERKGast", "BusinessNETZWERKGast")]
		BusinessNetzwerkGast = 100000022,
		
		/// <summary>
		/// BusinessNETZWERKMotoristik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Motoristik", 25, "", "BusinessNETZWERKMotoristik", "BusinessNETZWERKMotoristik")]
		BusinessNetzwerkMotoristik = 100000023,
		
		/// <summary>
		/// BusinessNETZWERKVertrieb
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Vertrieb", 26, "", "BusinessNETZWERKVertrieb", "BusinessNETZWERKVertrieb")]
		BusinessNetzwerkVertrieb = 100000024,
		
		/// <summary>
		/// buyflixxAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("buyflixx Ansprechpartner", 27, "", "buyflixxAP", "buyflixxAP")]
		BuyflixxAnsprechpartner = 100000025,
		
		/// <summary>
		/// DatenbeschaffungAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Datenbeschaffung Ansprechpartner", 28, "", "DatenbeschaffungAnsprechpartner", "DatenbeschaffungAnsprechpartner")]
		DatenbeschaffungAnsprechpartner = 100000027,
		
		/// <summary>
		/// DieBaugeraeteProfisBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Die Baugeräte Profis Beauftragter", 29, "", "DieBaugeraeteProfisBeauftragter", "DieBaugeraeteProfisBeauftragter")]
		DieBaugerTeProfisBeauftragter = 100000028,
		
		/// <summary>
		/// DieBaugeraeteProfisBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Die Baugeräte Profis Beirat", 30, "", "DieBaugeraeteProfisBeirat", "DieBaugeraeteProfisBeirat")]
		DieBaugerTeProfisBeirat = 100000029,
		
		/// <summary>
		/// DieSchweissProfisBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Die Schweiß Profis Beauftragter", 31, "", "DieSchweissProfisBeauftragter", "DieSchweissProfisBeauftragter")]
		DieSchweiProfisBeauftragter = 100000030,
		
		/// <summary>
		/// DieSchweissProfisBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Die Schweiß Profis Beirat", 32, "", "DieSchweissProfisBeirat", "DieSchweissProfisBeirat")]
		DieSchweiProfisBeirat = 100000031,
		
		/// <summary>
		/// DirektgeschaeftKfm
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direktgeschäft kfm.", 33, "", "DirektgeschaeftKfm", "DirektgeschaeftKfm")]
		DirektgeschFtKfm = 100000032,
		
		/// <summary>
		/// DirektgeschaeftVertrieb
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direktgeschäft Vertrieb", 34, "", "DirektgeschaeftVertrieb", "DirektgeschaeftVertrieb")]
		DirektgeschFtVertrieb = 100000033,
		
		/// <summary>
		/// Disponent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disponent", 35, "", "Disponent", "Disponent")]
		Disponent = 100000034,
		
		/// <summary>
		/// EBHAufsichtsrat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EBH Aufsichtsrat", 36, "", "EBHAufsichtsrat", "EBHAufsichtsrat")]
		EbhAufsichtsrat = 100000035,
		
		/// <summary>
		/// eCommerceAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eCommerce Ansprechpartner", 37, "", "eCommerceAnsprechpartner", "eCommerceAnsprechpartner")]
		EcommerceAnsprechpartner = 100000036,
		
		/// <summary>
		/// eDCBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC Beauftragter", 38, "", "eDCBeauftragter", "eDCBeauftragter")]
		EdcBeauftragter = 100000037,
		
		/// <summary>
		/// eDCFachlAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC fachl. Ansprechpartner", 39, "", "eDCFachlAnsprechpartner", "eDCFachlAnsprechpartner")]
		EdcFachlAnsprechpartner = 100000038,
		
		/// <summary>
		/// eDCKfmAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC kfm. Ansprechpartner", 40, "", "eDCKfmAnsprechpartner", "eDCKfmAnsprechpartner")]
		EdcKfmAnsprechpartner = 100000039,
		
		/// <summary>
		/// eDCTechAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC techn. Ansprechpartner", 41, "", "eDCTechAnsprechpartner", "eDCTechAnsprechpartner")]
		EdcTechnAnsprechpartner = 100000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI-Fehlerpostfach", 42, "#0000ff")]
		EdiFehlerpostfach = 100000149,
		
		/// <summary>
		/// eProcAnwender
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eProc Anwender", 43, "", "eProcAnwender", "eProcAnwender")]
		EprocAnwender = 100000041,
		
		/// <summary>
		/// ESHFKBleche
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH FK Bleche", 44, "", "ESHFKBleche", "ESHFKBleche")]
		EshFkBleche = 100000042,
		
		/// <summary>
		/// ESHFKEdelstahlAlu
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH FK Edelstahl / Alu", 45, "", "ESHFKEdelstahlAlu", "ESHFKEdelstahlAlu")]
		EshFkEdelstahlAlu = 100000043,
		
		/// <summary>
		/// ESHFKRohre
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH FK Rohre", 46, "", "ESHFKRohre", "ESHFKRohre")]
		EshFkRohre = 100000044,
		
		/// <summary>
		/// ESHFKTraegerStabstahl
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH FK Träger / Stabstahl", 47, "", "ESHFKTraegerStabstahl", "ESHFKTraegerStabstahl")]
		EshFkTrGerStabstahl = 100000045,
		
		/// <summary>
		/// ESH_Steel_Power
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Steel Power", 48, "", "ESH_Steel_Power", "ESH_Steel_Power")]
		EshSteelPower = 100000046,
		
		/// <summary>
		/// ESH_Strat_Kommission
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Strategie Kommission", 49, "", "ESH_Strat_Kommission", "ESH_Strat_Kommission")]
		EshStrategieKommission = 100000047,
		
		/// <summary>
		/// ETTBerater
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ETT Berater", 50, "", "ETTBerater", "ETTBerater")]
		EttBerater = 100000048,
		
		/// <summary>
		/// EURODIYBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY Beirat", 51, "", "EURODIYBeirat", "EURODIYBeirat")]
		EuroDiyBeirat = 100000049,
		
		/// <summary>
		/// ExpertenrundeAntriebstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expertenrunde Antriebstechnik", 52, "", "ExpertenrundeAntriebstechnik", "ExpertenrundeAntriebstechnik")]
		ExpertenrundeAntriebstechnik = 100000050,
		
		/// <summary>
		/// ExpertenrundeChemischTechnischeProdukte
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expertenrunde Chemisch Technische Produkte", 53, "", "ExpertenrundeChemischTechnischeProdukte", "ExpertenrundeChemischTechnischeProdukte")]
		ExpertenrundeChemischTechnischeProdukte = 100000051,
		
		/// <summary>
		/// ExpertenrundeDichtungstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expertenrunde Dichtungstechnik", 54, "", "ExpertenrundeDichtungstechnik", "ExpertenrundeDichtungstechnik")]
		ExpertenrundeDichtungstechnik = 100000052,
		
		/// <summary>
		/// ExpertenrundeSchlauchArmaturentechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expertenrunde Schlauch & Armaturentechnik", 55, "", "ExpertenrundeSchlauchArmaturentechnik", "ExpertenrundeSchlauchArmaturentechnik")]
		ExpertenrundeSchlauchArmaturentechnik = 100000053,
		
		/// <summary>
		/// FAVORITSprecherkreis
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FAVORIT Sprecherkreis", 56, "", "FAVORITSprecherkreis", "FAVORITSprecherkreis")]
		FavoritSprecherkreis = 100000054,
		
		/// <summary>
		/// FKBaugeraeteBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FK Baugeräte Beauftragter", 57, "", "FKBaugeraeteBeauftragter", "FKBaugeraeteBeauftragter")]
		FkBaugerTeBeauftragter = 100000055,
		
		/// <summary>
		/// FKBaugeraeteBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FK Baugeräte Beirat", 58, "", "FKBaugeraeteBeirat", "FKBaugeraeteBeirat")]
		FkBaugerTeBeirat = 100000056,
		
		/// <summary>
		/// FKBefestigungstechnikAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FK Befestigungstechnik Ansprechpartner", 59, "", "FKBefestigungstechnikAnsprechpartner", "FKBefestigungstechnikAnsprechpartner")]
		FkBefestigungstechnikAnsprechpartner = 100000057,
		
		/// <summary>
		/// FKTHAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FK TH Ansprechpartner", 60, "", "FKTHAnsprechpartner", "FKTHAnsprechpartner")]
		FkThAnsprechpartner = 100000058,
		
		/// <summary>
		/// FTHoldingBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FT-Holding-Beirat", 63, "", "FTHoldingBeirat", "FTHoldingBeirat")]
		FtHoldingBeirat = 100000061,
		
		/// <summary>
		/// FTHoldingGesellschafter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FT-Holding Gesellschafter", 61, "", "FTHoldingGesellschafter", "FTHoldingGesellschafter")]
		FtHoldingGesellschafter = 100000059,
		
		/// <summary>
		/// FTHoldingGesellschafterversammlung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FT-Holding Gesellschafterversammlung", 62, "", "FTHoldingGesellschafterversammlung", "FTHoldingGesellschafterversammlung")]
		FtHoldingGesellschafterversammlung = 100000060,
		
		/// <summary>
		/// GewemaAufsichtsrat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gewema Aufsichtsrat", 64, "", "GewemaAufsichtsrat", "GewemaAufsichtsrat")]
		GewemaAufsichtsrat = 100000062,
		
		/// <summary>
		/// GreenMotoBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GreenMoto Beirat", 65, "", "GreenMotoBeirat", "GreenMotoBeirat")]
		GreenmotoBeirat = 100000063,
		
		/// <summary>
		/// GreenMotoKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GreenMoto Konzeptbeauftragter", 66, "", "GreenMotoKonzeptbeauftragter", "GreenMotoKonzeptbeauftragter")]
		GreenmotoKonzeptbeauftragter = 100000064,
		
		/// <summary>
		/// HettichKonzeptAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hettich Konzept Ansprechpartner", 67, "", "HettichKonzeptAnsprechpartner", "HettichKonzeptAnsprechpartner")]
		HettichKonzeptAnsprechpartner = 100000065,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holzwerkzeuge Einkauf Ansprechpartner", 68, "#0000ff")]
		HolzwerkzeugeEinkaufAnsprechpartner = 100000150,
		
		/// <summary>
		/// HoppeKonzeptAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hoppe Konzept Ansprechpartner", 69, "", "HoppeKonzeptAnsprechpartner", "HoppeKonzeptAnsprechpartner")]
		HoppeKonzeptAnsprechpartner = 100000066,
		
		/// <summary>
		/// HWSBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWS Beirat", 70, "", "HWSBeirat", "HWSBeirat")]
		HwsBeirat = 100000067,
		
		/// <summary>
		/// HWSKompetenzgruppe
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWS Kompetenzgruppe", 71, "", "HWSKompetenzgruppe", "HWSKompetenzgruppe")]
		HwsKompetenzgruppe = 100000068,
		
		/// <summary>
		/// HWSKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWS Konzeptbeauftragter", 72, "", "HWSKonzeptbeauftragter", "HWSKonzeptbeauftragter")]
		HwsKonzeptbeauftragter = 100000069,
		
		/// <summary>
		/// HWZEinkaufAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWZ Einkauf Ansprechpartner", 73, "", "HWZEinkaufAnsprechpartner", "HWZEinkaufAnsprechpartner")]
		HwzEinkaufAnsprechpartner = 100000070,
		
		/// <summary>
		/// KatalogAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Katalog Ansprechpartner", 74, "", "KatalogAnsprechpartner", "KatalogAnsprechpartner")]
		KatalogAnsprechpartner = 100000071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 75)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// KGAusstellung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KG Ausstellung", 76, "", "KGAusstellung", "KGAusstellung")]
		KgAusstellung = 100000072,
		
		/// <summary>
		/// KGHolz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KG Holz", 77, "", "KGHolz", "KGHolz")]
		KgHolz = 100000073,
		
		/// <summary>
		/// KGIndustrietore
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KG Industrietore", 78, "", "KGIndustrietore", "KGIndustrietore")]
		KgIndustrietore = 100000074,
		
		/// <summary>
		/// KGMetallIndustrie
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KG Metall+Industrie", 79, "", "KGMetallIndustrie", "KGMetallIndustrie")]
		KgMetallIndustrie = 100000075,
		
		/// <summary>
		/// KGObjekt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KG Objekt", 80, "", "KGObjekt", "KGMetallIndustrie")]
		KgObjekt = 100000076,
		
		/// <summary>
		/// LeistungsgruppeEHH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Leistungsgruppe EHH", 81, "", "LeistungsgruppeEHH", "LeistungsgruppeEHH")]
		LeistungsgruppeEhh = 100000077,
		
		/// <summary>
		/// Lieferantenkorrekturen1Ansprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lieferantenkorrekturen 1. Ansprechpartner", 82, "", "Lieferantenkorrekturen1Ansprechpartner", "Lieferantenkorrekturen1Ansprechpartner")]
		Lieferantenkorrekturen1Ansprechpartner = 100000078,
		
		/// <summary>
		/// Lieferantenkorrekturen2Ansprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lieferantenkorrekturen 2. Ansprechpartner", 83, "", "Lieferantenkorrekturen2Ansprechpartner", "Lieferantenkorrekturen2Ansprechpartner")]
		Lieferantenkorrekturen2Ansprechpartner = 100000079,
		
		/// <summary>
		/// LogistikAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Logistik Ansprechpartner", 84, "", "LogistikAnsprechpartner", "LogistikAnsprechpartner")]
		LogistikAnsprechpartner = 100000080,
		
		/// <summary>
		/// LTWBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LTW Beirat", 85, "", "LTWBeirat", "LTWBeirat")]
		LtwBeirat = 100000081,
		
		/// <summary>
		/// MIETEplusBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MIETEplus Beirat", 86, "", "MIETEplusBeirat", "MIETEplusBeirat")]
		MieteplusBeirat = 100000082,
		
		/// <summary>
		/// MIETEplusMietdisponent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MIETEplus Mietdisponent", 87, "", "MIETEplusMietdisponent", "MIETEplusMietdisponent")]
		MieteplusMietdisponent = 100000083,
		
		/// <summary>
		/// MIETEplusMitarbeiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MIETEplus Mitarbeiter", 88, "", "MIETEplusMitarbeiter", "MIETEplusMitarbeiter")]
		MieteplusMitarbeiter = 100000084,
		
		/// <summary>
		/// MIETEplusVerantwortlicher
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MIETEplus Verantwortlicher", 89, "", "MIETEplusVerantwortlicher", "MIETEplusVerantwortlicher")]
		MieteplusVerantwortlicher = 100000085,
		
		/// <summary>
		/// MitgliedsbetreuungbeiLieferant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mitgliedsbetreuung bei Lieferant", 90, "", "MitgliedsbetreuungbeiLieferant", "MitgliedsbetreuungbeiLieferant")]
		MitgliedsbetreuungBeiLieferant = 100000086,
		
		/// <summary>
		/// PartnerBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Partner-Beirat", 91, "", "PartnerBeirat", "PartnerBeirat")]
		PartnerBeirat = 100000087,
		
		/// <summary>
		/// PIMBeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PIM Beauftragter", 92, "", "PIMBeauftragter", "PIMBeauftragter")]
		PimBeauftragter = 100000088,
		
		/// <summary>
		/// PLUS1Beirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PLUS1 Beirat", 94, "", "PLUS1Beirat", "PLUS1Beirat")]
		Plus1Beirat = 100000090,
		
		/// <summary>
		/// PLUS1Konzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PLUS 1 Konzeptbeauftragter", 93, "", "PLUS1Konzeptbeauftragter", "PLUS1Konzeptbeauftragter")]
		Plus1Konzeptbeauftragter = 100000089,
		
		/// <summary>
		/// PLUS1Sortimentskommission
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PLUS1 Sortimentskommission", 95, "", "PLUS1Sortimentskommission", "PLUS1Sortimentskommission")]
		Plus1Sortimentskommission = 100000091,
		
		/// <summary>
		/// PrecitoolBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Precitool Beirat", 96, "", "PrecitoolBeirat", "PrecitoolBeirat")]
		PrecitoolBeirat = 100000092,
		
		/// <summary>
		/// PreisabfrageAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preisabfrage Ansprechpartner", 97, "", "PreisabfrageAnsprechpartner", "PreisabfrageAnsprechpartner")]
		PreisabfrageAnsprechpartner = 100000093,
		
		/// <summary>
		/// PREMIUMASBeiratoperativ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM AS Beirat operativ", 98, "", "PREMIUMASBeiratoperativ", "PREMIUMASBeiratoperativ")]
		PremiumAsBeiratOperativ = 100000094,
		
		/// <summary>
		/// PREMIUMBEBeiratoperativ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM BE Beirat operativ", 99, "", "PREMIUMBEBeiratoperativ", "PREMIUMBEBeiratoperativ")]
		PremiumBeBeiratOperativ = 100000095,
		
		/// <summary>
		/// PREMIUMBeiratoperativ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM Beirat operativ", 101, "", "PREMIUMBeiratoperativ", "PREMIUMBeiratoperativ")]
		PremiumBeiratOperativ = 100000097,
		
		/// <summary>
		/// PREMIUMBeiratstrategisch
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM Beirat strategisch", 102, "", "PREMIUMBeiratstrategisch", "PREMIUMBeiratstrategisch")]
		PremiumBeiratStrategisch = 100000098,
		
		/// <summary>
		/// PREMIUMBEKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM BE Konzeptbeauftragter", 100, "", "PREMIUMBEKonzeptbeauftragter", "PREMIUMBEKonzeptbeauftragter")]
		PremiumBeKonzeptbeauftragter = 100000096,
		
		/// <summary>
		/// PREMIUMEWZBeiratoperativ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM EWZ Beirat operativ", 103, "", "PREMIUMEWZBeiratoperativ", "PREMIUMEWZBeiratoperativ")]
		PremiumEwzBeiratOperativ = 100000099,
		
		/// <summary>
		/// PREMIUMEWZKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM EWZ Konzeptbeauftragter", 104, "", "PREMIUMEWZKonzeptbeauftragter", "PREMIUMEWZKonzeptbeauftragter")]
		PremiumEwzKonzeptbeauftragter = 100000100,
		
		/// <summary>
		/// PREMIUMHWZSortimentsausschuss
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM HWZ Sortimentsausschuss", 105, "", "PREMIUMHWZSortimentsausschuss", "PREMIUMHWZSortimentsausschuss")]
		PremiumHwzSortimentsausschuss = 100000101,
		
		/// <summary>
		/// PREMIUMPWZSortimentsausschuss
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM PWZ Sortimentsausschuss", 106, "", "PREMIUMPWZSortimentsausschuss", "PREMIUMPWZSortimentsausschuss")]
		PremiumPwzSortimentsausschuss = 100000102,
		
		/// <summary>
		/// PROELEMENTAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PRO.ELEMENT Ansprechpartner", 107, "", "PROELEMENTAnsprechpartner", "PROELEMENTAnsprechpartner")]
		ProElementAnsprechpartner = 100000103,
		
		/// <summary>
		/// PROELEMENTBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PRO.ELEMENT Beirat", 108, "", "PROELEMENTBeirat", "PROELEMENTBeirat")]
		ProElementBeirat = 100000104,
		
		/// <summary>
		/// PVHFUTURECAMPBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE CAMP Beirat", 109, "", "PVHFUTURECAMPBeirat", "PVHFUTURECAMPBeirat")]
		PvhFutureCampBeirat = 100000105,
		
		/// <summary>
		/// PVHFUTURECAMPMitglied
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE CAMP Mitglied", 110, "", "PVHFUTURECAMPMitglied", "PVHFUTURECAMPMitglied")]
		PvhFutureCampMitglied = 100000106,
		
		/// <summary>
		/// PVHFUTURELABGruender
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE LAB Gründer", 111, "", "PVHFUTURELABGruender", "PVHFUTURELABGruender")]
		PvhFutureLabGrNder = 100000107,
		
		/// <summary>
		/// PVHFUTURELABMitglied
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE LAB Mitglied", 112, "", "PVHFUTURELABMitglied", "PVHFUTURELABMitglied")]
		PvhFutureLabMitglied = 100000108,
		
		/// <summary>
		/// QualifizierungAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualifizierung Ansprechpartner", 113, "", "QualifizierungAnsprechpartner", "QualifizierungAnsprechpartner")]
		QualifizierungAnsprechpartner = 100000109,
		
		/// <summary>
		/// Rapid3DAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rapid3D Ansprechpartner", 114, "", "Rapid3DAnsprechpartner", "Rapid3DAnsprechpartner")]
		Rapid3dAnsprechpartner = 100000110,
		
		/// <summary>
		/// Reklamation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reklamation", 115, "", "Reklamation", "Reklamation")]
		Reklamation = 100000111,
		
		/// <summary>
		/// sellflixxCustomerProtectionAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sellflixx Customer Protection Ansprechpartner", 116, "", "sellflixxCustomerProtectionAP", "sellflixxCustomerProtectionAP")]
		SellflixxCustomerProtectionAnsprechpartner = 100000112,
		
		/// <summary>
		/// sellflixxExpectedProductsAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sellflixx Expected Products Ansprechpartner", 117, "", "sellflixxExpectedProductsAP", "sellflixxExpectedProductsAP")]
		SellflixxExpectedProductsAnsprechpartner = 100000113,
		
		/// <summary>
		/// sellflixxPROFITGUIDEAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sellflixx PROFIT GUIDE Ansprechpartner", 118, "", "sellflixxPROFITGUIDEAnsprechpartner", "sellflixxPROFITGUIDEAnsprechpartner")]
		SellflixxProfitGuideAnsprechpartner = 100000114,
		
		/// <summary>
		/// sellflixxRecommendationsAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sellflixx Recommendations Ansprechpartner", 119, "", "sellflixxRecommendationsAP", "sellflixxRecommendationsAP")]
		SellflixxRecommendationsAnsprechpartner = 100000115,
		
		/// <summary>
		/// sellflixxRecommendationsMsAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sellflixx Recommendations Multishop Ansprechpartner", 120, "", "sellflixxRecommendationsMsAP", "sellflixxRecommendationsMsAP")]
		SellflixxRecommendationsMultishopAnsprechpartner = 100000116,
		
		/// <summary>
		/// SortimentsfindungAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sortimentsfindung Ansprechpartner", 121, "", "SortimentsfindungAnsprechpartner", "SortimentsfindungAnsprechpartner")]
		SortimentsfindungAnsprechpartner = 100000117,
		
		/// <summary>
		/// Stammdatenpflege
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stammdatenpflege", 122, "", "Stammdatenpflege", "Stammdatenpflege")]
		Stammdatenpflege = 100000118,
		
		/// <summary>
		/// techflixxBodyTempScanAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("techflixx BodyTempScan Ansprechpartner", 123, "", "techflixxBodyTempScanAP", "techflixxBodyTempScanAP")]
		TechflixxBodytempscanAnsprechpartner = 100000119,
		
		/// <summary>
		/// TechnischerHandelBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel Beirat", 124, "", "TechnischerHandelBeirat", "TechnischerHandelBeirat")]
		TechnischerHandelBeirat = 100000120,
		
		/// <summary>
		/// TechnischerHandelBonusLIEF
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel Bonus LIEF", 125, "", "TechnischerHandelBonusLIEF", "TechnischerHandelBonusLIEF")]
		TechnischerHandelBonusLief = 100000121,
		
		/// <summary>
		/// TechnischerHandelBonusMGL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel Bonus MGL", 126, "", "TechnischerHandelBonusMGL")]
		TechnischerHandelBonusMgl = 100000122,
		
		/// <summary>
		/// TechnischerHandelFKTagung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel FK Tagung", 127, "", "TechnischerHandelFKTagung", "TechnischerHandelFKTagung")]
		TechnischerHandelFkTagung = 100000123,
		
		/// <summary>
		/// TechnischerHandelFORMATIndustrietechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel FORMAT Industrietechnik", 128, "", "TechnischerHandelFORMATIndustrietechnik", "TechnischerHandelFORMATIndustrietechnik")]
		TechnischerHandelFormatIndustrietechnik = 100000124,
		
		/// <summary>
		/// ToolineoBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Toolineo Beirat", 129, "", "ToolineoBeirat", "ToolineoBeirat")]
		ToolineoBeirat = 100000125,
		
		/// <summary>
		/// UNIONBEBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION BE Beirat", 130, "", "UNIONBEBeirat", "UNIONBEBeirat")]
		UnionBeBeirat = 100000126,
		
		/// <summary>
		/// UNIONBEKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION BE Konzeptbeauftragter", 131, "", "UNIONBEKonzeptbeauftragter", "UNIONBEKonzeptbeauftragter")]
		UnionBeKonzeptbeauftragter = 100000127,
		
		/// <summary>
		/// UNIONEWZBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION EWZ Beirat", 132, "", "UNIONEWZBeirat", "UNIONEWZBeirat")]
		UnionEwzBeirat = 100000128,
		
		/// <summary>
		/// UNIONEWZKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION EWZ Konzeptbeauftragter", 133, "", "UNIONEWZKonzeptbeauftragter", "UNIONEWZKonzeptbeauftragter")]
		UnionEwzKonzeptbeauftragter = 100000129,
		
		/// <summary>
		/// KonzeptbeauftragterUNIONPro
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION Pro Konzeptbeauftragter", 134, "", "KonzeptbeauftragterUNIONPro", "KonzeptbeauftragterUNIONPro")]
		UnionProKonzeptbeauftragter = 100000130,
		
		/// <summary>
		/// UNIONWHBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION WH Beirat", 135, "", "UNIONWHBeirat", "UNIONWHBeirat")]
		UnionWhBeirat = 100000131,
		
		/// <summary>
		/// UNIONWHKonzeptbeauftragter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UNION WH Konzeptbeauftragter", 136, "", "UNIONWHKonzeptbeauftragter", "UNIONWHKonzeptbeauftragter")]
		UnionWhKonzeptbeauftragter = 100000132,
		
		/// <summary>
		/// Wareneingang
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wareneingang", 137, "", "Wareneingang", "Wareneingang")]
		Wareneingang = 100000133,
		
		/// <summary>
		/// WMBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WM Beirat", 138, "", "WMBeirat", "WMBeirat")]
		WmBeirat = 100000134,
		
		/// <summary>
		/// WMWerbekommission
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WM Werbekommission", 139, "", "WMWerbekommission", "WMWerbekommission")]
		WmWerbekommission = 100000135,
		
		/// <summary>
		/// workflixxCatchTalentsAP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("workflixx Catch Talents Ansprechpartner", 140, "", "workflixxCatchTalentsAP", "workflixxCatchTalentsAP")]
		WorkflixxCatchTalentsAnsprechpartner = 100000136,
		
		/// <summary>
		/// workflixxDokuneoAnsprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("workflixx Dokuneo Ansprechpartner", 141, "", "workflixxDokuneoAnsprechpartner", "workflixxDokuneoAnsprechpartner")]
		WorkflixxDokuneoAnsprechpartner = 100000137,
		
		/// <summary>
		/// WRAusstellungsmitarbeiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Ausstellungsmitarbeiter", 142, "", "WRAusstellungsmitarbeiter", "WRAusstellungsmitarbeiter")]
		WrAusstellungsmitarbeiter = 100000138,
		
		/// <summary>
		/// WRBeirat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Beirat", 143, "", "WRBeirat", "WRBeirat")]
		WrBeirat = 100000139,
		
		/// <summary>
		/// WREinkaufVertrieb
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Einkauf+Vertrieb", 144, "", "WREinkaufVertrieb", "WREinkaufVertrieb")]
		WrEinkaufVertrieb = 100000140,
		
		/// <summary>
		/// WRFORMAT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR FORMAT", 145, "", "WRFORMAT", "WRFORMAT")]
		WrFormat = 100000141,
		
		/// <summary>
		/// WRKompetenzteamLager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Kompetenzteam Lager", 146, "", "WRKompetenzteamLager", "WRKompetenzteamLager")]
		WrKompetenzteamLager = 100000142,
		
		/// <summary>
		/// WRLGEHH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR-LG EHH", 150, "", "WRLGEHH", "WRLGEHH")]
		WrLgEhh = 100000146,
		
		/// <summary>
		/// WRProduktausschussHeizung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Produktausschuss Heizung", 147, "", "WRProduktausschussHeizung", "WRProduktausschussHeizung")]
		WrProduktausschussHeizung = 100000143,
		
		/// <summary>
		/// WRProduktausschussInstallation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Produktausschuss Installation", 148, "", "WRProduktausschussInstallation", "WRProduktausschussInstallation")]
		WrProduktausschussInstallation = 100000144,
		
		/// <summary>
		/// WRProduktausschussSanitaer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Produktausschuss Sanitär", 149, "", "WRProduktausschussSanitaer", "WRProduktausschussSanitaer")]
		WrProduktausschussSanitR = 100000145,
	}
}
#pragma warning restore CS1591
