#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_Interests_C
	{
		
		/// <summary>
		/// AusuWeiterbildung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aus- u. Weiterbildung", 0, "", "AusuWeiterbildung", "AusuWeiterbildung")]
		AusUWeiterbildung = 100000001,
		
		/// <summary>
		/// BranchentreffSpezial
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Branchentreff Spezial", 1, "", "BranchentreffSpezial", "BranchentreffSpezial")]
		BranchentreffSpezial = 100000002,
		
		/// <summary>
		/// BranchentreffTotal
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Branchentreff Total", 2, "", "BranchentreffTotal", "BranchentreffTotal")]
		BranchentreffTotal = 100000003,
		
		/// <summary>
		/// BusinessNETZWERK1
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 1", 3, "", "BusinessNETZWERK1", "BusinessNETZWERK1")]
		BusinessNetzwerk1 = 100000004,
		
		/// <summary>
		/// BusinessNETZWERK10
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 10", 11, "", "BusinessNETZWERK10", "BusinessNETZWERK10")]
		BusinessNetzwerk10 = 100000005,
		
		/// <summary>
		/// BusinessNETZWERK11
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 11", 12, "", "BusinessNETZWERK11", "BusinessNETZWERK11")]
		BusinessNetzwerk11 = 100000006,
		
		/// <summary>
		/// BusinessNETZWERK12
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 12", 13, "", "BusinessNETZWERK12", "BusinessNETZWERK12")]
		BusinessNetzwerk12 = 100000007,
		
		/// <summary>
		/// BusinessNETZWERK2
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 2", 4, "", "BusinessNETZWERK2", "BusinessNETZWERK2")]
		BusinessNetzwerk2 = 100000008,
		
		/// <summary>
		/// BusinessNETZWERK3
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 3", 5, "", "BusinessNETZWERK3", "BusinessNETZWERK3")]
		BusinessNetzwerk3 = 100000009,
		
		/// <summary>
		/// BusinessNETZWERK4
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 4", 6, "", "BusinessNETZWERK4", "BusinessNETZWERK4")]
		BusinessNetzwerk4 = 100000010,
		
		/// <summary>
		/// BusinessNETZWERK5
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 5", 7, "", "BusinessNETZWERK5", "BusinessNETZWERK5")]
		BusinessNetzwerk5 = 100000011,
		
		/// <summary>
		/// BusinessNETZWERK6
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 6", 8, "", "BusinessNETZWERK6", "BusinessNETZWERK6")]
		BusinessNetzwerk6 = 100000012,
		
		/// <summary>
		/// BusinessNETZWERK7
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 7", 9, "", "BusinessNETZWERK7", "BusinessNETZWERK7")]
		BusinessNetzwerk7 = 100000013,
		
		/// <summary>
		/// BusinessNETZWERK8
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK 8", 10, "", "BusinessNETZWERK8", "BusinessNETZWERK8")]
		BusinessNetzwerk8 = 100000014,
		
		/// <summary>
		/// BusinessNETZWERKallg
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK allg.", 14, "", "BusinessNETZWERKallg", "BusinessNETZWERKallg")]
		BusinessNetzwerkAllg = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Baubeschlag", 15, "#0000ff")]
		BusinessNetzwerkBaubeschlag = 100000092,
		
		/// <summary>
		/// BusinessNETZWERKMotoristik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Motoristik", 16, "", "BusinessNETZWERKMotoristik", "BusinessNETZWERKMotoristik")]
		BusinessNetzwerkMotoristik = 100000016,
		
		/// <summary>
		/// BusinessNETZWERKVertrieb
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business NETZWERK Vertrieb", 17, "", "BusinessNETZWERKVertrieb", "BusinessNETZWERKVertrieb")]
		BusinessNetzwerkVertrieb = 100000017,
		
		/// <summary>
		/// BVBLoge
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BVB Loge", 18, "", "BVBLoge", "BVBLoge")]
		BvbLoge = 100000018,
		
		/// <summary>
		/// Datenmanagement
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Datenmanagement", 19, "", "Datenmanagement", "Datenmanagement")]
		Datenmanagement = 100000019,
		
		/// <summary>
		/// eCommerce
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eCommerce", 21, "", "eCommerce", "eCommerce")]
		Ecommerce = 100000021,
		
		/// <summary>
		/// eDC
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC", 22, "", "eDC", "eDC")]
		Edc = 100000022,
		
		/// <summary>
		/// EDEInternationalBonusanschreiben
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDE International Bonusanschreiben", 23, "", "EDEInternationalBonusanschreiben", "EDEInternationalBonusanschreiben")]
		EdeInternationalBonusanschreiben = 100000023,
		
		/// <summary>
		/// Einkaufsoffensive
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Einkaufsoffensive", 24, "", "Einkaufsoffensive", "Einkaufsoffensive")]
		Einkaufsoffensive = 100000024,
		
		/// <summary>
		/// Eisenwarenmesse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eisenwarenmesse", 25, "", "Eisenwarenmesse", "Eisenwarenmesse")]
		Eisenwarenmesse = 100000025,
		
		/// <summary>
		/// ELearning
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("E-Learning", 20, "", "ELearning", "ELearning")]
		ELearning = 100000020,
		
		/// <summary>
		/// eProc
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eProc", 26, "", "eProc", "eProc")]
		Eproc = 100000026,
		
		/// <summary>
		/// ESHBetonstahl
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Betonstahl", 27, "", "ESHBetonstahl", "ESHBetonstahl")]
		EshBetonstahl = 100000027,
		
		/// <summary>
		/// ESHBleche
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Bleche", 28, "", "ESHBleche", "ESHBleche")]
		EshBleche = 100000028,
		
		/// <summary>
		/// ESHEdelstahl
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Edelstahl", 29, "", "ESHEdelstahl", "ESHEdelstahl")]
		EshEdelstahl = 100000029,
		
		/// <summary>
		/// ESH_Einladung_Dialog
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Einladung Dialog", 30, "", "ESH_Einladung_Dialog", "ESH_Einladung_Dialog")]
		EshEinladungDialog = 100000030,
		
		/// <summary>
		/// ESHForum
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Forum", 31, "", "ESHForum", "ESHForum")]
		EshForum = 100000031,
		
		/// <summary>
		/// ESHInfo
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Info", 32, "", "ESHInfo", "ESHInfo")]
		EshInfo = 100000032,
		
		/// <summary>
		/// ESHRegioBayern
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio Bayern", 33, "", "ESHRegioBayern", "ESHRegioBayern")]
		EshRegioBayern = 100000033,
		
		/// <summary>
		/// ESHRegioBodensee
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio Bodensee", 34, "", "ESHRegioBodensee", "ESHRegioBodensee")]
		EshRegioBodensee = 100000034,
		
		/// <summary>
		/// ESHRegioFrankfurt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio Frankfurt", 35, "", "ESHRegioFrankfurt", "ESHRegioFrankfurt")]
		EshRegioFrankfurt = 100000035,
		
		/// <summary>
		/// ESHRegioHannover
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio Hannover", 36, "", "ESHRegioHannover", "ESHRegioHannover")]
		EshRegioHannover = 100000036,
		
		/// <summary>
		/// ESHRegioNord
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio Nord", 37, "", "ESHRegioNord", "ESHRegioNord")]
		EshRegioNord = 100000037,
		
		/// <summary>
		/// ESHRegioWest
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Regio West", 38, "", "ESHRegioWest", "ESHRegioWest")]
		EshRegioWest = 100000038,
		
		/// <summary>
		/// ESHRohre
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Rohre", 39, "", "ESHRohre", "ESHRohre")]
		EshRohre = 100000039,
		
		/// <summary>
		/// ESHStabstahlTraeger
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH Stabstahl Träger", 40, "", "ESHStabstahlTraeger", "ESHStabstahlTraeger")]
		EshStabstahlTrGer = 100000040,
		
		/// <summary>
		/// ETT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ETT", 41, "", "ETT", "ETT")]
		Ett = 100000041,
		
		/// <summary>
		/// ExpertentageBefestigungstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expertentage Befestigungstechnik", 42, "", "ExpertentageBefestigungstechnik", "ExpertentageBefestigungstechnik")]
		ExpertentageBefestigungstechnik = 100000042,
		
		/// <summary>
		/// FBNews
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FB News", 43, "", "FBNews", "FBNews")]
		FbNews = 100000043,
		
		/// <summary>
		/// FBSchulung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FB Schulung", 44, "", "FBSchulung", "FBSchulung")]
		FbSchulung = 100000044,
		
		/// <summary>
		/// FORUMBauelemente
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FORUM Bauelemente", 45, "", "FORUMBauelemente", "FORUMBauelemente")]
		ForumBauelemente = 100000045,
		
		/// <summary>
		/// FotostudioMusterbestellung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fotostudio Musterbestellung", 46, "", "FotostudioMusterbestellung", "FotostudioMusterbestellung")]
		FotostudioMusterbestellung = 100000046,
		
		/// <summary>
		/// GalaBau
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gala Bau", 47, "", "GalaBau", "GalaBau")]
		GalaBau = 100000047,
		
		/// <summary>
		/// GreenMotoAnsprechpartnerLieferant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GreenMoto Ansprechpartner Lieferant", 48, "", "GreenMotoAnsprechpartnerLieferant", "GreenMotoAnsprechpartnerLieferant")]
		GreenmotoAnsprechpartnerLieferant = 100000048,
		
		/// <summary>
		/// Herbsoffensive
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Herbsoffensive", 49, "", "Herbsoffensive", "Herbsoffensive")]
		Herbsoffensive = 100000049,
		
		/// <summary>
		/// HWSAnsprechpartnerLieferant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HWS Ansprechpartner Lieferant", 50, "", "HWSAnsprechpartnerLieferant", "HWSAnsprechpartnerLieferant")]
		HwsAnsprechpartnerLieferant = 100000050,
		
		/// <summary>
		/// Innovationsbroschuere
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Innovationsbroschüre", 51, "", "Innovationsbroschuere", "Innovationsbroschuere")]
		InnovationsbroschRe = 100000051,
		
		/// <summary>
		/// IntMarktplatzAT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Int. Marktplatz AT", 52, "", "IntMarktplatzAT", "IntMarktplatzAT")]
		IntMarktplatzAt = 100000052,
		
		/// <summary>
		/// IntMarktplatzCZSK
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Int. Marktplatz CZ / SK", 53, "", "IntMarktplatzCZSK", "IntMarktplatzCZSK")]
		IntMarktplatzCzSk = 100000053,
		
		/// <summary>
		/// IntMarktplatzPL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Int. Marktplatz PL", 54, "", "IntMarktplatzPL", "IntMarktplatzCZSK")]
		IntMarktplatzPl = 100000054,
		
		/// <summary>
		/// ISOZertifizierung9001
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ISO Zertifizierung 9001", 55, "", "ISOZertifizierung9001", "ISOZertifizierung9001")]
		IsoZertifizierung9001 = 100000055,
		
		/// <summary>
		/// Jubilaeum25JahreFKSchweisstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Jubiläum 25 Jahre FK Schweißtechnik", 56, "", "Jubilaeum25JahreFKSchweisstechnik", "Jubilaeum25JahreFKSchweisstechnik")]
		JubilUm25JahreFkSchweiTechnik = 100000056,
		
		/// <summary>
		/// Katalog
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Katalog", 57, "", "Katalog", "Katalog")]
		Katalog = 100000057,
		
		/// <summary>
		/// KatalogArbeitsschutz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Katalog Arbeitsschutz", 58, "", "KatalogArbeitsschutz", "KatalogArbeitsschutz")]
		KatalogArbeitsschutz = 100000058,
		
		/// <summary>
		/// Katalogportal
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Katalogportal", 59, "", "Katalogportal", "Katalogportal")]
		Katalogportal = 100000059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 92)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// MarktplatzBaugeraete
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marktplatz Baugeräte", 60, "", "MarktplatzBaugeraete", "MarktplatzBaugeraete")]
		MarktplatzBaugerTe = 100000060,
		
		/// <summary>
		/// MarktplatzDieSchweissProfis
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marktplatz Die Schweiß-Profis", 61, "", "MarktplatzDieSchweissProfis", "MarktplatzDieSchweissProfis")]
		MarktplatzDieSchweiProfis = 100000061,
		
		/// <summary>
		/// MarktplatzPREMIUMAzubi
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marktplatz PREMIUM Azubi", 62, "", "MarktplatzPREMIUMAzubi", "MarktplatzPREMIUMAzubi")]
		MarktplatzPremiumAzubi = 100000062,
		
		/// <summary>
		/// MarktplatzPREMIUMBeNeLux
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marktplatz PREMIUM BeNeLux", 63, "", "MarktplatzPREMIUMBeNeLux", "MarktplatzPREMIUMBeNeLux")]
		MarktplatzPremiumBenelux = 100000063,
		
		/// <summary>
		/// MarktplatzUNIONWZH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marktplatz UNION WZH", 64, "", "MarktplatzUNIONWZH", "MarktplatzUNIONWZH")]
		MarktplatzUnionWzh = 100000064,
		
		/// <summary>
		/// OnlineShop
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Online-Shop", 65, "", "OnlineShop", "OnlineShop")]
		OnlineShop = 100000065,
		
		/// <summary>
		/// PIM
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PIM", 66, "", "PIM", "PIM")]
		Pim = 100000066,
		
		/// <summary>
		/// PLUS1AnsprechpartnerLieferant
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PLUS 1 Ansprechpartner Lieferant", 67, "", "PLUS1AnsprechpartnerLieferant", "PLUS1AnsprechpartnerLieferant")]
		Plus1AnsprechpartnerLieferant = 100000067,
		
		/// <summary>
		/// PREMIUMGesamttagung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM Gesamttagung", 68, "", "PREMIUMGesamttagung", "PREMIUMGesamttagung")]
		PremiumGesamttagung = 100000068,
		
		/// <summary>
		/// PREMIUMVertriebsinformationen
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PREMIUM Vertriebsinformationen", 69, "", "PREMIUMVertriebsinformationen", "PREMIUMVertriebsinformationen")]
		PremiumVertriebsinformationen = 100000069,
		
		/// <summary>
		/// ProfiEventBG
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Profi Event BG", 70, "", "ProfiEventBG", "ProfiEventBG")]
		ProfiEventBg = 100000070,
		
		/// <summary>
		/// ProfiEventST
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Profi Event ST", 71, "", "ProfiEventST", "ProfiEventST")]
		ProfiEventSt = 100000071,
		
		/// <summary>
		/// ProfitageBefestigungstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Profitage Befestigungstechnik", 72, "", "ProfitageBefestigungstechnik", "ProfitageBefestigungstechnik")]
		ProfitageBefestigungstechnik = 100000072,
		
		/// <summary>
		/// Prospekt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prospekt", 73, "", "Prospekt", "Prospekt")]
		Prospekt = 100000073,
		
		/// <summary>
		/// PVHFUTURECAMP
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE CAMP", 74, "", "PVHFUTURECAMP", "PVHFUTURECAMP")]
		PvhFutureCamp = 100000074,
		
		/// <summary>
		/// PVHFUTURELAB
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH FUTURE LAB", 75, "", "PVHFUTURELAB", "PVHFUTURELAB")]
		PvhFutureLab = 100000075,
		
		/// <summary>
		/// PVHMag
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH Mag Anzeigen", 76, "", "PVHMag", "PVHMag")]
		PvhMagAnzeigen = 100000076,
		
		/// <summary>
		/// Rapid3D
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rapid3D", 77, "", "Rapid3D", "Rapid3D")]
		Rapid3d = 100000077,
		
		/// <summary>
		/// RFID
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RFID", 78, "", "RFID", "RFID")]
		Rfid = 100000078,
		
		/// <summary>
		/// Sammelkaeufe
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sammelkäufe", 79, "", "Sammelkaeufe", "Sammelkaeufe")]
		SammelkUfe = 100000079,
		
		/// <summary>
		/// Scanner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Scanner", 80, "", "Scanner", "Scanner")]
		Scanner = 100000080,
		
		/// <summary>
		/// SystemAKArbeitsschutz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("System AK Arbeitsschutz", 81, "", "SystemAKArbeitsschutz", "SystemAKArbeitsschutz")]
		SystemAkArbeitsschutz = 100000081,
		
		/// <summary>
		/// VertriebsforumArbeitsschutz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vertriebsforum Arbeitsschutz", 82, "", "VertriebsforumArbeitsschutz", "VertriebsforumArbeitsschutz")]
		VertriebsforumArbeitsschutz = 100000082,
		
		/// <summary>
		/// VTKIndustriebedarf
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("VTK Industriebedarf", 83, "", "VTKIndustriebedarf", "VTKIndustriebedarf")]
		VtkIndustriebedarf = 100000083,
		
		/// <summary>
		/// Werkzeugforum
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Werkzeugforum", 84, "", "Werkzeugforum", "Werkzeugforum")]
		Werkzeugforum = 100000084,
		
		/// <summary>
		/// WREHHVertriebstage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR EHH Vertriebstage", 85, "", "WREHHVertriebstage", "WREHHVertriebstage")]
		WrEhhVertriebstage = 100000085,
		
		/// <summary>
		/// WRFruehjahrstagung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Frühjahrstagung", 86, "", "WRFruehjahrstagung", "WRFruehjahrstagung")]
		WrFrHjahrstagung = 100000086,
		
		/// <summary>
		/// WRIFHMesse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR IFH Messe", 87, "", "WRIFHMesse", "WRIFHMesse")]
		WrIfhMesse = 100000087,
		
		/// <summary>
		/// WRISHMesse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR ISH Messe", 88, "", "WRISHMesse", "WRISHMesse")]
		WrIshMesse = 100000088,
		
		/// <summary>
		/// WRMitgliederversammlung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR Mitgliederversammlung", 89, "", "WRMitgliederversammlung", "WRMitgliederversammlung")]
		WrMitgliederversammlung = 100000089,
		
		/// <summary>
		/// WRSHKMesse
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WR SHK Messe", 90, "", "WRSHKMesse", "WRSHKMesse")]
		WrShkMesse = 100000090,
		
		/// <summary>
		/// ZukunftsforumTechnischerHandel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zukunftsforum Technischer Handel", 91, "", "ZukunftsforumTechnischerHandel", "ZukunftsforumTechnischerHandel")]
		ZukunftsforumTechnischerHandel = 100000091,
	}
}
#pragma warning restore CS1591
