#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_GoodsArea_C
	{
		
		/// <summary>
		/// Arbeitsschutz
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Arbeitsschutz", 2, "", "Arbeitsschutz", "Arbeitsschutz")]
		Arbeitsschutz = 100000001,
		
		/// <summary>
		/// BaubeschlaegeSicherheitstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Baubeschläge Sicherheitstechnik", 3, "", "BaubeschlaegeSicherheitstechnik", "BaubeschlaegeSicherheitstechnik")]
		BaubeschlGeSicherheitstechnik = 100000002,
		
		/// <summary>
		/// Bauelemente
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bauelemente", 4, "", "Bauelemente", "Bauelemente")]
		Bauelemente = 100000003,
		
		/// <summary>
		/// Baugeraete
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Baugeräte", 5, "", "Baugeraete", "Baugeraete")]
		BaugerTe = 100000004,
		
		/// <summary>
		/// Befestigungstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Befestigungstechnik", 6, "", "Befestigungstechnik", "Befestigungstechnik")]
		Befestigungstechnik = 100000005,
		
		/// <summary>
		/// BeiratAdorf
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Beirat/Adorf", 7, "", "BeiratAdorf", "BeiratAdorf")]
		BeiratAdorf = 100000006,
		
		/// <summary>
		/// Betriebseinrichtung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Betriebseinrichtung", 8, "", "Betriebseinrichtung", "Betriebseinrichtung")]
		Betriebseinrichtung = 100000007,
		
		/// <summary>
		/// CMGarten
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CM Garten", 9, "", "CMGarten", "CMGarten")]
		CmGarten = 100000008,
		
		/// <summary>
		/// CMTechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CM Technik", 10, "", "CMTechnik", "CMTechnik")]
		CmTechnik = 100000009,
		
		/// <summary>
		/// CMWohnen
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CM Wohnen", 11, "", "CMWohnen", "CMWohnen")]
		CmWohnen = 100000010,
		
		/// <summary>
		/// eCommerce
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eCommerce", 12, "", "eCommerce", "eCommerce")]
		Ecommerce = 100000011,
		
		/// <summary>
		/// eDCHaustechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eDC Haustechnik", 13, "", "eDCHaustechnik", "eDCHaustechnik")]
		EdcHaustechnik = 100000012,
		
		/// <summary>
		/// EDEInternational
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDE International", 14, "", "EDEInternational", "EDEInternational")]
		EdeInternational = 100000013,
		
		/// <summary>
		/// EDI Ansprechpartner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI Ansprechpartner", 15, "#0000ff", "EDI Ansprechpartner", "EDI Ansprechpartner")]
		EdiAnsprechpartner = 100000039,
		
		/// <summary>
		/// EDI Fehlerbericht
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EDI Fehlerbericht", 16, "#0000ff", "EDI Fehlerbericht", "EDI Fehlerbericht")]
		EdiFehlerbericht = 100000049,
		
		/// <summary>
		/// ElektroDruckluftwerkzeuge
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Elektro- Druckluftwerkzeuge", 17, "", "ElektroDruckluftwerkzeuge", "ElektroDruckluftwerkzeuge")]
		ElektroDruckluftwerkzeuge = 100000014,
		
		/// <summary>
		/// ESH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ESH", 18, "", "ESH", "ESH")]
		Esh = 100000015,
		
		/// <summary>
		/// EURODIY
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EURO-DIY", 19, "", "EURODIY", "EURODIY")]
		EuroDiy = 100000016,
		
		/// <summary>
		/// FacilityManagement
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Facility Management", 20, "", "FacilityManagement", "FacilityManagement")]
		FacilityManagement = 100000017,
		
		/// <summary>
		/// GBME
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GB ME", 21, "", "GBME", "GBME")]
		GbMe = 100000018,
		
		/// <summary>
		/// GF1
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 1", 22, "", "GF1", "GF1")]
		Gf1 = 100000019,
		
		/// <summary>
		/// GF2
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 2", 23, "", "GF2", "GF2")]
		Gf2 = 100000020,
		
		/// <summary>
		/// GF3
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 3", 24, "", "GF3", "GF3")]
		Gf3 = 100000021,
		
		/// <summary>
		/// GF4
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 4", 25, "", "GF4", "GF4")]
		Gf4 = 100000022,
		
		/// <summary>
		/// GF5
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 5", 26, "", "GF5", "GF5")]
		Gf5 = 100000023,
		
		/// <summary>
		/// GF6
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GF 6", 27, "", "GF6", "GF6")]
		Gf6 = 100000024,
		
		/// <summary>
		/// Handwerkzeuge
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Handwerkzeuge", 28, "", "Handwerkzeuge", "Handwerkzeuge")]
		Handwerkzeuge = 100000025,
		
		/// <summary>
		/// Haustechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Haustechnik", 29, "", "Haustechnik", "Haustechnik")]
		Haustechnik = 100000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 49)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// Logistik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Logistik", 30, "", "Logistik", "Logistik")]
		Logistik = 100000027,
		
		/// <summary>
		/// Marketing
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marketing", 31, "", "Marketing", "Marketing")]
		Marketing = 100000028,
		
		/// <summary>
		/// Moebelbeschlaege
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Möbelbeschläge", 33, "", "Moebelbeschlaege", "Moebelbeschlaege")]
		MBelbeschlGe = 100000030,
		
		/// <summary>
		/// Motoristik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Motoristik", 32, "", "Motoristik", "Motoristik")]
		Motoristik = 100000029,
		
		/// <summary>
		/// NHW
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NHW", 34, "", "NHW", "NHW")]
		Nhw = 100000031,
		
		/// <summary>
		/// OrganisationIT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Organisation/IT", 35, "", "OrganisationIT", "OrganisationIT")]
		OrganisationIt = 100000032,
		
		/// <summary>
		/// Personal
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Personal", 36, "", "Personal", "Personal")]
		Personal = 100000033,
		
		/// <summary>
		/// Prozessmanagement
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prozessmanagement", 37, "", "Prozessmanagement", "Prozessmanagement")]
		Prozessmanagement = 100000034,
		
		/// <summary>
		/// Praezisionswerkzeuge
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Präzisionswerkzeuge", 38, "", "Praezisionswerkzeuge", "Praezisionswerkzeuge")]
		PrZisionswerkzeuge = 100000035,
		
		/// <summary>
		/// PVHSysteme
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PVH-Systeme", 39, "", "PVHSysteme", "PVHSysteme")]
		PvhSysteme = 100000036,
		
		/// <summary>
		/// RechtCompliance
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Recht & Compliance", 40, "", "RechtCompliance", "RechtCompliance")]
		RechtCompliance = 100000037,
		
		/// <summary>
		/// Schweisstechnik
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Schweißtechnik", 41, "", "Schweisstechnik", "Schweisstechnik")]
		SchweiTechnik = 100000038,
		
		/// <summary>
		/// ServiceCenter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service Center", 42, "", "ServiceCenter", "ServiceCenter")]
		ServiceCenter = 100000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stahl", 0, "#0000ff", "", "Stahl")]
		Stahl = 100000048,
		
		/// <summary>
		/// StationaereMaschinenMetall
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stationäre Maschinen Metall", 43, "", "StationaereMaschinenMetall", "StationaereMaschinenMetall")]
		StationReMaschinenMetall = 100000041,
		
		/// <summary>
		/// StiftungETrautwein
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stiftung/E.Trautwein", 44, "", "StiftungETrautwein", "StiftungETrautwein")]
		StiftungETrautwein = 100000042,
		
		/// <summary>
		/// Strategieimplementierung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Strategieimplementierung", 45, "", "Strategieimplementierung", "Strategieimplementierung")]
		Strategieimplementierung = 100000043,
		
		/// <summary>
		/// TechnischerHandel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technischer Handel", 46, "", "TechnischerHandel", "TechnischerHandel")]
		TechnischerHandel = 100000044,
		
		/// <summary>
		/// Toolineo
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Toolineo", 47, "", "Toolineo", "Toolineo")]
		Toolineo = 100000045,
		
		/// <summary>
		/// Versorgungsnetzwerke
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Versorgungsnetzwerke", 48, "", "Versorgungsnetzwerke", "Versorgungsnetzwerke")]
		Versorgungsnetzwerke = 100000046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Werkzeuge/Maschinen für die Holzbearbeitung", 1, "#0000ff", "", "WerkzeugeMaschinenfuerdieHolzbearbeitung")]
		WerkzeugeMaschinenFRDieHolzbearbeitung = 100000047,
	}
}
#pragma warning restore CS1591
