#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_Title_Norm_C
	{
		
		/// <summary>
		/// BA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BA", 3, "", "BA", "BA")]
		Ba = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("B. Eng.", 2, "#0000ff", "", "BEng")]
		BEng = 100000042,
		
		/// <summary>
		/// Betriebsw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Betriebsw.", 4, "", "Betriebsw", "Betriebsw")]
		Betriebsw = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Betriebsw. BA", 1, "#0000ff", "", "BetriebswBA")]
		BetriebswBa = 100000041,
		
		/// <summary>
		/// Betriebsw.VWA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Betriebsw. (VWA)", 5, "", "Betriebsw.VWA", "Betriebsw.VWA")]
		BetriebswVwa = 100000003,
		
		/// <summary>
		/// DiplBetriebsw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Betriebsw.", 6, "", "DiplBetriebsw", "DiplBetriebsw")]
		DiplBetriebsw = 100000004,
		
		/// <summary>
		/// DiplBetriebswBA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Betriebsw. (BA)", 7, "", "DiplBetriebswBA", "DiplBetriebswBA")]
		DiplBetriebswBa = 100000005,
		
		/// <summary>
		/// DiplBetriebswFH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Betriebsw. (FH)", 8, "", "DiplBetriebswFH", "DiplBetriebswFH")]
		DiplBetriebswFh = 100000006,
		
		/// <summary>
		/// DiplInf
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Inf.", 9, "", "DiplInf", "DiplInf")]
		DiplInf = 100000007,
		
		/// <summary>
		/// DiplIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Ing.", 10, "", "DiplIng", "DiplIng")]
		DiplIng = 100000008,
		
		/// <summary>
		/// DiplIngBetriebsw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Ing.-Betriebsw.", 12, "", "DiplIngBetriebsw", "DiplIngBetriebsw")]
		DiplIngBetriebsw = 100000010,
		
		/// <summary>
		/// DiplIngFH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Ing. (FH)", 11, "", "DiplIngFH", "DiplIngFH")]
		DiplIngFh = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Ing.- Ökon.", 0, "#0000ff", "", "DiplIngOekon")]
		DiplIngKon = 100000040,
		
		/// <summary>
		/// DiplIngOec
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Ing.-Oec.", 13, "", "DiplIngOec", "DiplIngOec")]
		DiplIngOec = 100000011,
		
		/// <summary>
		/// DiplKffr
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Kffr.", 14, "", "DiplKffr", "DiplKffr")]
		DiplKffr = 100000012,
		
		/// <summary>
		/// DiplKfm
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Kfm.", 15, "", "DiplKfm", "DiplKfm")]
		DiplKfm = 100000013,
		
		/// <summary>
		/// DiplKfmFH
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Kfm. (FH)", 16, "", "DiplKfmFH", "DiplKfmFH")]
		DiplKfmFh = 100000014,
		
		/// <summary>
		/// DiplOec
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Oec.", 17, "", "DiplOec", "DiplOec")]
		DiplOec = 100000015,
		
		/// <summary>
		/// DiplVolksw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Volksw.", 18, "", "DiplVolksw", "DiplVolksw")]
		DiplVolksw = 100000016,
		
		/// <summary>
		/// DiplWirt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Wirt.", 19, "", "DiplWirt", "DiplWirt")]
		DiplWirt = 100000017,
		
		/// <summary>
		/// DiplWirtInf
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Wirt.-Inf.", 20, "", "DiplWirtInf", "DiplWirtInf")]
		DiplWirtInf = 100000018,
		
		/// <summary>
		/// DiplWirtIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dipl.-Wirt.-Ing.", 21, "", "DiplWirtIng", "DiplWirtIng")]
		DiplWirtIng = 100000019,
		
		/// <summary>
		/// Dr
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr.", 22, "", "Dr", "Dr")]
		Dr = 100000020,
		
		/// <summary>
		/// DrIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr.-Ing.", 26, "", "DrIng", "DrIng")]
		DrIng = 100000024,
		
		/// <summary>
		/// DrIngDiplKfm
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr.-Ing. Dipl. Kfm.", 27, "", "DrIngDiplKfm", "DrIngDiplKfm")]
		DrIngDiplKfm = 100000025,
		
		/// <summary>
		/// Drjur
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr. jur.", 23, "", "Drjur", "Drjur")]
		DrJur = 100000021,
		
		/// <summary>
		/// DrRerNat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr. rer. nat.", 24, "", "DrRerNat", "DrRerNat")]
		DrRerNat = 100000022,
		
		/// <summary>
		/// Drrerpol
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dr. rer. pol.", 25, "", "Drrerpol", "Drrerpol")]
		DrRerPol = 100000023,
		
		/// <summary>
		/// Handelsfachw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Handelsfachw.", 28, "", "Handelsfachw", "Handelsfachw")]
		Handelsfachw = 100000026,
		
		/// <summary>
		/// Ing
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ing.", 29, "", "Ing", "Ing")]
		Ing = 100000027,
		
		/// <summary>
		/// IngDiplBetriebsw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ing.-Dipl.-Betriebsw.", 30, "", "IngDiplBetriebsw", "IngDiplBetriebsw")]
		IngDiplBetriebsw = 100000028,
		
		/// <summary>
		/// ITSystemIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IT System Ing.", 31, "", "ITSystemIng", "ITSystemIng")]
		ItSystemIng = 100000029,
		
		/// <summary>
		/// MA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("M.A.", 32, "", "MA", "MA")]
		MA = 100000030,
		
		/// <summary>
		/// Mag
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mag.", 36, "", "Mag", "Mag")]
		Mag = 100000034,
		
		/// <summary>
		/// MAIntBusiness
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("M.A. Int. Business", 33, "", "MAIntBusiness", "MAIntBusiness")]
		MAIntBusiness = 100000031,
		
		/// <summary>
		/// MEng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("M.Eng.", 34, "", "MEng", "MEng")]
		MEng = 100000032,
		
		/// <summary>
		/// MSc
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("M.Sc.", 35, "", "MSc", "MSc")]
		MSc = 100000033,
		
		/// <summary>
		/// ProfDr
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prof. Dr.", 37, "", "ProfDr", "ProfDr")]
		ProfDr = 100000035,
		
		/// <summary>
		/// ProfDrIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prof. Dr. Ing.", 38, "", "ProfDrIng", "ProfDrIng")]
		ProfDrIng = 100000036,
		
		/// <summary>
		/// ProfessorEhSenatorEhEhDiplIng
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Professor E.h. Senator E.h. E.h. Dipl.-Ing.", 39, "", "ProfessorEhSenatorEhEhDiplIng", "ProfessorEhSenatorEhEhDiplIng")]
		ProfessorEHSenatorEHEHDiplIng = 100000037,
		
		/// <summary>
		/// staatlgeprBautechniker
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("staatl. gepr. Bautechniker", 40, "", "staatlgeprBautechniker", "staatlgeprBautechniker")]
		StaatlGeprBautechniker = 100000038,
		
		/// <summary>
		/// staatlgeprBetriebsw
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("staatl. gepr. Betriebsw.", 41, "", "staatlgeprBetriebsw", "staatlgeprBetriebsw")]
		StaatlGeprBetriebsw = 100000039,
	}
}
#pragma warning restore CS1591
