#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_Pos_Company_Norm_C
	{
		
		/// <summary>
		/// Aufsichtsrat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aufsichtsrat", 1, "", "Aufsichtsrat", "Aufsichtsrat")]
		Aufsichtsrat = 100000001,
		
		/// <summary>
		/// BereichsleitungAbteilungsleitung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bereichsleitung/Abteilungsleitung", 2, "", "BereichsleitungAbteilungsleitung", "BereichsleitungAbteilungsleitung")]
		BereichsleitungAbteilungsleitung = 100000002,
		
		/// <summary>
		/// GeschaeftsfuehrerVorstandrechtlselbstNL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("*Geschäftsführer/Vorstand rechtl. selbst. NL", 3, "", "GeschaeftsfuehrerVorstandrechtlselbstNL", "GeschaeftsfuehrerVorstandrechtlselbstNL")]
		GeschFtsfHrerVorstandRechtlSelbstNl = 100000003,
		
		/// <summary>
		/// GeschaeftsfuehrungVorstand
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("*Geschäftsführung/Vorstand", 4, "", "GeschaeftsfuehrungVorstand", "GeschaeftsfuehrungVorstand")]
		GeschFtsfHrungVorstand = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Geschäftsleitung", 0, "#0000ff", "", "Geschaeftsleitung")]
		GeschFtsleitung = 100000009,
		
		/// <summary>
		/// Mitarbeiter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mitarbeiter", 5, "", "Mitarbeiter", "Mitarbeiter")]
		Mitarbeiter = 100000005,
		
		/// <summary>
		/// Partner
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Partner", 6, "", "Partner", "Partner")]
		Partner = 100000006,
		
		/// <summary>
		/// Prokurist
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prokurist", 7, "", "Prokurist", "Prokurist")]
		Prokurist = 100000007,
		
		/// <summary>
		/// TeamleitungGruppenleitung
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teamleitung/Gruppenleitung", 8, "", "TeamleitungGruppenleitung", "TeamleitungGruppenleitung")]
		TeamleitungGruppenleitung = 100000008,
	}
}
#pragma warning restore CS1591
