#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_UserLang_ComMu_2_C
	{
		
		/// <summary>
		/// BG
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BG", 0, "", "BG", "BG")]
		Bg = 100000001,
		
		/// <summary>
		/// CZ
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CZ", 1, "", "CZ", "CZ")]
		Cz = 100000002,
		
		/// <summary>
		/// DE
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DE", 2, "", "DE", "DE")]
		De = 100000003,
		
		/// <summary>
		/// DK
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DK", 3, "", "DK", "DK")]
		Dk = 100000004,
		
		/// <summary>
		/// EN
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EN", 4, "", "EN", "EN")]
		En = 100000005,
		
		/// <summary>
		/// ES
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ES", 5, "", "ES", "ES")]
		Es = 100000006,
		
		/// <summary>
		/// FR
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FR", 6, "", "FR", "FR")]
		Fr = 100000007,
		
		/// <summary>
		/// HU
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HU", 7, "", "HU", "HU")]
		Hu = 100000008,
		
		/// <summary>
		/// IT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IT", 8, "", "IT", "IT")]
		It = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keine Daten im PoC", 19)]
		KeineDatenImPoc = 100000000,
		
		/// <summary>
		/// LV
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LV", 9, "", "LV", "LV")]
		Lv = 100000026,
		
		/// <summary>
		/// NL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NL", 10, "", "NL", "NL")]
		Nl = 100000009,
		
		/// <summary>
		/// NO
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NO", 11, "", "NO", "NO")]
		No = 100000010,
		
		/// <summary>
		/// PL
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PL", 12, "", "PL", "PL")]
		Pl = 100000011,
		
		/// <summary>
		/// PT
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PT", 13, "", "PT", "PT")]
		Pt = 100000012,
		
		/// <summary>
		/// RO
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RO", 14, "", "RO", "RO")]
		Ro = 100000013,
		
		/// <summary>
		/// SE
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SE", 15, "", "SE", "SE")]
		Se = 100000014,
		
		/// <summary>
		/// SI
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SI", 16, "", "SI", "SI")]
		Si = 100000015,
		
		/// <summary>
		/// SK
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SK", 17, "", "SK", "SK")]
		Sk = 100000016,
		
		/// <summary>
		/// TR
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TR", 18, "", "TR", "TR")]
		Tr = 100000017,
	}
}
#pragma warning restore CS1591
