#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum New_Md_PreIsKLasSe_C
	{
		
		/// <summary>
		/// klasse2
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" 1.000 € - 1.500 €", 1, "", "klasse2", "klasse2")]
		_10001500 = 2,
		
		/// <summary>
		/// klasse3
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" 1.500 € - 2.000 €", 2, "", "klasse3", "klasse3")]
		_15002000 = 3,
		
		/// <summary>
		/// klasse4
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" mehr als 2.000 €", 3, "", "klasse4", "klasse4")]
		MehrAls2000 = 4,
		
		/// <summary>
		/// klasse1
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" weniger als 1.000 €", 0, "", "klasse1", "klasse1")]
		WenigerAls1000 = 1,
	}
}
#pragma warning restore CS1591
