#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Beitrag: Nachrichtentyp "Privat" oder "Direkt".
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SocialActivity_PostMessageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Private Nachricht", 1)]
		PrivateMessage = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Öffentliche Nachricht", 0)]
		PublicMessage = 0,
	}
}
#pragma warning restore CS1591
